// Code generated by scripts/build_scaffold_assets.mjs; DO NOT EDIT.
"use strict";
(() => {
  // packages/redevplugin-ui/src/error-codes.gen.ts
  var pluginBridgeErrorCodes = [
    "PLUGIN_INVALID_REQUEST",
    "PLUGIN_MANIFEST_INVALID",
    "PLUGIN_PACKAGE_INVALID",
    "PLUGIN_PACKAGE_TOO_LARGE",
    "PLUGIN_PACKAGE_PATH_FORBIDDEN",
    "PLUGIN_SIGNATURE_INVALID",
    "PLUGIN_TRUST_STATE_DENIED",
    "PLUGIN_TRUST_VERIFICATION_REQUIRED",
    "PLUGIN_TRUST_VERIFICATION_INVALID",
    "PLUGIN_RELEASE_REF_VERIFICATION_FAILED",
    "PLUGIN_RELEASE_REF_POLICY_DENIED",
    "PLUGIN_DISABLED",
    "PLUGIN_DISABLED_BY_POLICY",
    "PLUGIN_PERMISSION_DENIED",
    "PLUGIN_CONFIRMATION_REQUIRED",
    "PLUGIN_CONFIRMATION_INVALID",
    "PLUGIN_TOKEN_EXPIRED",
    "PLUGIN_TOKEN_REPLAY",
    "PLUGIN_GATEWAY_TOKEN_INVALID",
    "PLUGIN_GATEWAY_TOKEN_REPLAYED",
    "PLUGIN_GATEWAY_TOKEN_CHANNEL_MISMATCH",
    "PLUGIN_ASSET_TICKET_INVALID",
    "PLUGIN_ASSET_SESSION_INVALID",
    "PLUGIN_STREAM_TICKET_INVALID",
    "PLUGIN_STREAM_DELIVERY_INVALID",
    "PLUGIN_STREAM_CANCELLED",
    "PLUGIN_LEASE_INVALID",
    "PLUGIN_LEASE_REPLAYED",
    "PLUGIN_GRANT_INVALID",
    "PLUGIN_STORAGE_QUOTA_EXCEEDED",
    "PLUGIN_OPERATION_BLOCKED",
    "PLUGIN_OPERATION_NOT_FOUND",
    "PLUGIN_OPERATION_NOT_CANCELABLE",
    "PLUGIN_NETWORK_TARGET_DENIED",
    "PLUGIN_NETWORK_RATE_LIMITED",
    "PLUGIN_RUNTIME_UNAVAILABLE",
    "PLUGIN_RUNTIME_VERSION_MISMATCH",
    "PLUGIN_UI_PROTOCOL_UNSUPPORTED",
    "PLUGIN_UI_PROTOCOL_VIOLATION",
    "PLUGIN_SURFACE_QUIESCE_TIMEOUT",
    "PLUGIN_JSON_LIMIT_EXCEEDED",
    "PLUGIN_CAPABILITY_ERROR",
    "PLUGIN_WORKER_ERROR",
    "PLUGIN_CONTRACT_MISMATCH",
    "PLUGIN_MANAGEMENT_REVISION_MISMATCH",
    "PLUGIN_AUTHORIZATION_REVISION_MISMATCH",
    "PLUGIN_BINDING_REVISION_MISMATCH",
    "PLUGIN_VALUES_REVISION_MISMATCH",
    "PLUGIN_CSRF_REQUIRED",
    "PLUGIN_CONFIRMATION_REJECTED",
    "PLUGIN_BRIDGE_TIMEOUT",
    "PLUGIN_BRIDGE_DISPOSED",
    "PLUGIN_BRIDGE_HANDSHAKE_FAILED",
    "PLUGIN_BRIDGE_HANDSHAKE_REQUIRED"
  ];

  // packages/redevplugin-ui/src/errors.ts
  var PluginBridgeError = class extends Error {
    errorCode;
    data;
    details;
    mutationOutcome;
    constructor(errorCode, message, data, details, mutationOutcome) {
      super(message);
      this.name = "PluginBridgeError";
      this.errorCode = errorCode;
      this.data = data;
      this.details = details ?? data;
      this.mutationOutcome = mutationOutcome;
    }
  };

  // packages/redevplugin-ui/src/opaque-surface-policy.gen.ts
  var opaqueSurfaceAllowedTags = [
    "main",
    "section",
    "header",
    "footer",
    "nav",
    "aside",
    "article",
    "div",
    "span",
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "button",
    "input",
    "textarea",
    "select",
    "option",
    "label",
    "fieldset",
    "legend",
    "form",
    "ul",
    "ol",
    "li",
    "dl",
    "dt",
    "dd",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "caption",
    "details",
    "summary",
    "pre",
    "code",
    "kbd",
    "samp",
    "strong",
    "em",
    "small",
    "mark",
    "time",
    "progress",
    "meter",
    "img",
    "picture",
    "source",
    "audio",
    "video",
    "track",
    "canvas"
  ];
  var opaqueSurfaceGlobalAttributes = [
    "id",
    "class",
    "role",
    "title",
    "hidden",
    "tabindex",
    "autofocus",
    "lang",
    "dir",
    "data-redevplugin-action",
    "data-redevplugin-escape-action",
    "data-redevplugin-asset-binding",
    "data-redevplugin-asset-attr"
  ];
  var opaqueSurfaceTagAttributes = {
    "button": [
      "type",
      "name",
      "value",
      "disabled",
      "aria-pressed",
      "aria-expanded"
    ],
    "input": [
      "type",
      "name",
      "value",
      "checked",
      "disabled",
      "readonly",
      "required",
      "placeholder",
      "min",
      "max",
      "step",
      "autocomplete"
    ],
    "textarea": [
      "name",
      "value",
      "disabled",
      "readonly",
      "required",
      "placeholder",
      "rows",
      "cols",
      "maxlength"
    ],
    "select": [
      "name",
      "disabled",
      "required",
      "multiple",
      "size"
    ],
    "option": [
      "value",
      "selected",
      "disabled",
      "label"
    ],
    "label": [
      "for"
    ],
    "form": [
      "name",
      "autocomplete"
    ],
    "th": [
      "scope",
      "colspan",
      "rowspan"
    ],
    "td": [
      "colspan",
      "rowspan"
    ],
    "progress": [
      "value",
      "max"
    ],
    "meter": [
      "value",
      "min",
      "max",
      "low",
      "high",
      "optimum"
    ],
    "img": [
      "alt",
      "width",
      "height",
      "loading",
      "decoding"
    ],
    "audio": [
      "controls",
      "autoplay",
      "muted",
      "loop",
      "preload"
    ],
    "video": [
      "controls",
      "autoplay",
      "muted",
      "loop",
      "preload",
      "width",
      "height",
      "playsinline"
    ],
    "source": [
      "type",
      "media"
    ],
    "track": [
      "kind",
      "srclang",
      "label",
      "default"
    ],
    "time": [
      "datetime"
    ],
    "canvas": [
      "width",
      "height",
      "data-redevplugin-canvas"
    ]
  };
  var opaqueSurfaceSafeInputTypes = [
    "text",
    "search",
    "number",
    "checkbox",
    "radio",
    "button",
    "submit",
    "reset"
  ];
  var opaqueSurfaceRenderLimits = {
    "max_message_bytes": 262144,
    "max_in_flight_requests": 256,
    "max_renders_per_second": 60,
    "max_render_depth": 32,
    "max_render_nodes": 4096,
    "max_attributes_per_element": 64,
    "max_text_length": 65536,
    "max_attribute_value_length": 4096,
    "max_form_fields": 128,
    "max_canvas_count": 4,
    "max_canvas_dimension": 4096,
    "max_canvas_total_pixels": 16777216,
    "max_canvas_pointer_events_per_second": 120,
    "max_image_count": 32,
    "max_image_dimension": 4096,
    "max_image_total_pixels": 33554432,
    "worker_heartbeat_interval_ms": 1e4,
    "worker_heartbeat_timeout_ms": 5e3
  };

  // packages/redevplugin-ui/src/http.ts
  function isRecord(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
  }
  function hasExactKeys(value, keys) {
    if (!isRecord(value)) return false;
    const actual = Object.keys(value).sort();
    const expected = [...keys].sort();
    return actual.length === expected.length && actual.every((key, index) => key === expected[index]);
  }
  function hasAllowedKeys(value, keys) {
    return isRecord(value) && Object.keys(value).every((key) => keys.includes(key));
  }

  // packages/redevplugin-ui/src/surface-scope.ts
  var registrations = /* @__PURE__ */ new WeakMap();
  var PluginSurfaceScope = class _PluginSurfaceScope {
    constructor() {
      registrations.set(this, /* @__PURE__ */ new Map());
    }
    static create() {
      return new _PluginSurfaceScope();
    }
  };
  function createPluginSurfaceScope() {
    return PluginSurfaceScope.create();
  }
  var defaultPluginSurfaceScope = createPluginSurfaceScope();

  // packages/redevplugin-ui/src/ui-patch-validator.ts
  var PluginUIReconcileError = class extends Error {
    constructor(message) {
      super(message);
      this.name = "PluginUIReconcileError";
    }
  };
  var keyPattern = new RegExp("^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$");
  var identifierPattern = new RegExp("^[A-Za-z0-9._:-]{1,128}$");
  var opaqueHandlePattern = new RegExp("^[A-Za-z0-9_-]{8,160}$");
  var allowedTags = new Set(opaqueSurfaceAllowedTags);
  var globalAttributes = new Set(opaqueSurfaceGlobalAttributes);
  var safeInputTypes = new Set(opaqueSurfaceSafeInputTypes);
  var tagAttributes = new Map(
    Object.entries(opaqueSurfaceTagAttributes).map(([tag, attributes]) => [tag, new Set(attributes)])
  );
  function validatePluginUITree(tree) {
    if (!isElement(tree)) {
      throw new PluginUIReconcileError("Plugin UI root must be one keyed element");
    }
    const keys = /* @__PURE__ */ new Set();
    const ancestors = /* @__PURE__ */ new Set();
    let nodes = 0;
    const visit = (node, depth) => {
      nodes += 1;
      if (nodes > opaqueSurfaceRenderLimits.max_render_nodes || depth > opaqueSurfaceRenderLimits.max_render_depth) {
        throw new PluginUIReconcileError("Plugin UI tree exceeds structural limits");
      }
      if (typeof node === "string") {
        if (node.length > opaqueSurfaceRenderLimits.max_text_length) throw new PluginUIReconcileError("Plugin UI text exceeds limits");
        return;
      }
      if (!isElement(node) || ancestors.has(node)) {
        throw new PluginUIReconcileError("Plugin UI tree must contain plain acyclic VNodes");
      }
      ancestors.add(node);
      try {
        if (!keyPattern.test(node.key) || keys.has(node.key)) {
          throw new PluginUIReconcileError(`Plugin UI key is invalid or duplicated: ${String(node.key)}`);
        }
        keys.add(node.key);
        if (!allowedTags.has(node.tag)) {
          throw new PluginUIReconcileError(`Plugin UI tag is not allowed for ${node.key}`);
        }
        if (node.attributes !== void 0) {
          if (!isPlainRecord(node.attributes) || Object.keys(node.attributes).length > opaqueSurfaceRenderLimits.max_attributes_per_element) {
            throw new PluginUIReconcileError(`Plugin UI attributes are invalid for ${node.key}`);
          }
          for (const [name, value] of Object.entries(node.attributes)) {
            if (!validAttribute(node.tag, name, value)) {
              throw new PluginUIReconcileError(`Plugin UI attribute ${name} is not allowed for ${node.key}`);
            }
          }
        }
        if (node.children !== void 0) {
          if (!Array.isArray(node.children)) throw new PluginUIReconcileError(`Plugin UI children are invalid for ${node.key}`);
          for (const child of node.children) visit(child, depth + 1);
        }
      } finally {
        ancestors.delete(node);
      }
    };
    visit(tree, 1);
    return tree;
  }
  function isElement(value) {
    if (!isPlainRecord(value)) return false;
    return Object.keys(value).every((key) => ["type", "key", "tag", "attributes", "children"].includes(key)) && value.type === "element" && typeof value.key === "string" && typeof value.tag === "string";
  }
  function isPlainRecord(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  }
  function validAttribute(tag, name, value) {
    const normalized = name.toLowerCase();
    if (normalized.startsWith("on") || ["style", "src", "srcset", "href", "srcdoc", "action", "formaction"].includes(normalized)) {
      return false;
    }
    if (!globalAttributes.has(normalized) && !normalized.startsWith("aria-") && !tagAttributes.get(tag)?.has(normalized)) {
      return false;
    }
    if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") return false;
    if (typeof value === "number" && !Number.isFinite(value)) return false;
    const serialized = String(value);
    if (normalized === "data-redevplugin-action" || normalized === "data-redevplugin-escape-action") {
      if (!identifierPattern.test(serialized)) return false;
    }
    if (normalized === "data-redevplugin-asset-binding") {
      if (!serialized.startsWith("asset_") || !opaqueHandlePattern.test(serialized)) return false;
    }
    if (normalized === "data-redevplugin-asset-attr" && serialized !== "src" && serialized !== "poster") return false;
    if (normalized === "data-redevplugin-canvas" && (tag !== "canvas" || !keyPattern.test(serialized))) return false;
    if (tag === "canvas" && (normalized === "width" || normalized === "height") && (!/^[1-9][0-9]{0,4}$/.test(serialized) || Number(serialized) > opaqueSurfaceRenderLimits.max_canvas_dimension)) return false;
    if (tag === "input" && normalized === "type" && !safeInputTypes.has(serialized.trim().toLowerCase() || "text")) return false;
    return serialized.length <= opaqueSurfaceRenderLimits.max_attribute_value_length;
  }

  // packages/redevplugin-ui/src/ui-reconciler.ts
  var editableValueTags = /* @__PURE__ */ new Set(["input", "textarea", "select", "option"]);
  var maxPluginUIPatchOperations = 1024;
  function reconcilePluginUITrees(current, next, options = {}) {
    validatePluginUITree(current);
    validatePluginUITree(next);
    if (current.key !== next.key || current.tag !== next.tag) {
      throw new PluginUIReconcileError("Plugin UI root key and tag are immutable");
    }
    const operations = [];
    const transferredCanvasKeys = options.transferredCanvasKeys ?? /* @__PURE__ */ new Set();
    const maxOperations = options.maxOperations ?? maxPluginUIPatchOperations;
    if (!Number.isSafeInteger(maxOperations) || maxOperations < 1 || maxOperations > maxPluginUIPatchOperations) {
      throw new PluginUIReconcileError(`Plugin UI maxOperations must be an integer between 1 and ${maxPluginUIPatchOperations}`);
    }
    const append = (operation) => {
      if (operations.length >= maxOperations) {
        throw new PluginUIReconcileError("Plugin UI patch exceeds the operation limit");
      }
      operations.push(operation);
    };
    const ensureCanvasStable = (node, action) => {
      if (typeof node === "string") return;
      if (transferredCanvasKeys.has(node.key)) {
        throw new PluginUIReconcileError(`Transferred canvas ${node.key} cannot be ${action}`);
      }
      for (const child of node.children ?? []) ensureCanvasStable(child, action);
    };
    const reconcileElement = (left, right) => {
      if (left.key !== right.key || left.tag !== right.tag) {
        throw new PluginUIReconcileError(`Plugin UI element identity changed for ${left.key}`);
      }
      reconcileAttributes(left, right, options.controlEditRevisions, append);
      const working = [...left.children ?? []];
      const desired = right.children ?? [];
      if (operations.length + estimateKeyedStructuralOperations(working, desired) > maxOperations) {
        throw new PluginUIReconcileError("Plugin UI patch exceeds the operation limit");
      }
      const desiredIndexByKey = keyedChildIndexes(desired);
      for (let index = working.length - 1; index >= 0; index -= 1) {
        const child = working[index];
        if (typeof child === "string") continue;
        const desiredIndex = desiredIndexByKey.get(child.key);
        const desiredChild = desiredIndex === void 0 ? void 0 : desired[desiredIndex];
        if (typeof desiredChild !== "string" && desiredChild?.tag === child.tag) continue;
        ensureCanvasStable(child, desiredIndex === void 0 ? "removed" : "replaced");
        append({ type: "remove_child", parent_key: left.key, child_index: index, child_key: child.key });
        working.splice(index, 1);
      }
      const workingIndexByKey = keyedChildIndexes(working);
      const refreshWorkingIndexes = (start, end = working.length - 1) => {
        for (let index = Math.max(0, start); index <= Math.min(end, working.length - 1); index += 1) {
          const child = working[index];
          if (typeof child !== "string") workingIndexByKey.set(child.key, index);
        }
      };
      for (let index = 0; index < working.length; index += 1) {
        const child = working[index];
        if (typeof child !== "string" && transferredCanvasKeys.has(child.key)) {
          const nextIndex = desiredIndexByKey.get(child.key) ?? -1;
          if (nextIndex === -1) throw new PluginUIReconcileError(`Transferred canvas ${child.key} cannot be removed`);
          if (nextIndex !== index) throw new PluginUIReconcileError(`Transferred canvas ${child.key} cannot be moved`);
        }
      }
      if (fullyKeyed(working) && fullyKeyed(desired)) {
        reconcileKeyedChildren(left.key, working, desired, ensureCanvasStable, append);
        for (let index = 0; index < desired.length; index += 1) {
          const present = working[index];
          const wanted = desired[index];
          if (present === void 0 || present.key !== wanted.key || present.tag !== wanted.tag) {
            throw new PluginUIReconcileError("Plugin UI keyed reconciliation became inconsistent");
          }
          reconcileElement(present, wanted);
          working[index] = wanted;
        }
        return;
      }
      for (let index = 0; index < desired.length; index += 1) {
        const wanted = desired[index];
        const present = working[index];
        if (typeof wanted === "string") {
          if (typeof present === "string") {
            if (present !== wanted) append({ type: "set_text", parent_key: left.key, child_index: index, text: wanted });
            working[index] = wanted;
          } else {
            append({ type: "insert_child", parent_key: left.key, child_index: index, node: wanted });
            working.splice(index, 0, wanted);
            refreshWorkingIndexes(index);
          }
          continue;
        }
        const foundIndex = typeof present !== "string" && present?.key === wanted.key ? index : workingIndexByKey.get(wanted.key) ?? -1;
        if (foundIndex === -1) {
          append({ type: "insert_child", parent_key: left.key, child_index: index, node: wanted });
          working.splice(index, 0, wanted);
          refreshWorkingIndexes(index);
          continue;
        }
        const found = working[foundIndex];
        if (typeof found === "string") throw new PluginUIReconcileError("Plugin UI keyed lookup became inconsistent");
        if (found.tag !== wanted.tag) {
          ensureCanvasStable(found, "replaced");
          append({ type: "remove_child", parent_key: left.key, child_index: foundIndex, child_key: found.key });
          working.splice(foundIndex, 1);
          workingIndexByKey.delete(found.key);
          refreshWorkingIndexes(foundIndex);
          append({ type: "insert_child", parent_key: left.key, child_index: index, node: wanted });
          working.splice(index, 0, wanted);
          refreshWorkingIndexes(index);
          continue;
        }
        if (foundIndex !== index) {
          ensureCanvasStable(found, "moved");
          append({ type: "move_child", parent_key: left.key, child_key: found.key, from_index: foundIndex, to_index: index });
          working.splice(foundIndex, 1);
          working.splice(index, 0, found);
          refreshWorkingIndexes(Math.min(foundIndex, index), Math.max(foundIndex, index));
        }
        reconcileElement(found, wanted);
        working[index] = wanted;
      }
      for (let index = working.length - 1; index >= desired.length; index -= 1) {
        const removed = working[index];
        ensureCanvasStable(removed, "removed");
        append({
          type: "remove_child",
          parent_key: left.key,
          child_index: index,
          ...typeof removed === "string" ? {} : { child_key: removed.key }
        });
        working.splice(index, 1);
        if (typeof removed !== "string") workingIndexByKey.delete(removed.key);
      }
    };
    reconcileElement(current, next);
    return operations;
  }
  function keyedChildIndexes(children) {
    const indexes = /* @__PURE__ */ new Map();
    for (let index = 0; index < children.length; index += 1) {
      const child = children[index];
      if (typeof child !== "string") indexes.set(child.key, index);
    }
    return indexes;
  }
  function fullyKeyed(children) {
    return children.every((child) => typeof child !== "string");
  }
  function reconcileKeyedChildren(parentKey, working, desired, ensureCanvasStable, append) {
    const workingIndexByKey = keyedChildIndexes(working);
    const retainedDesiredIndexes = [];
    const retainedWorkingIndexes = [];
    for (let desiredIndex = 0; desiredIndex < desired.length; desiredIndex += 1) {
      const currentIndex = workingIndexByKey.get(desired[desiredIndex].key);
      if (currentIndex !== void 0) {
        retainedDesiredIndexes.push(desiredIndex);
        retainedWorkingIndexes.push(currentIndex);
      }
    }
    const stableDesiredIndexes = new Set(
      longestIncreasingSubsequenceIndexes(retainedWorkingIndexes).map((retainedIndex) => retainedDesiredIndexes[retainedIndex])
    );
    const refreshWorkingIndexes = (start) => {
      for (let index = Math.max(0, start); index < working.length; index += 1) {
        workingIndexByKey.set(working[index].key, index);
      }
    };
    for (let desiredIndex = desired.length - 1; desiredIndex >= 0; desiredIndex -= 1) {
      const wanted = desired[desiredIndex];
      const foundIndex = workingIndexByKey.get(wanted.key);
      const anchor = desired[desiredIndex + 1];
      const anchorIndex = anchor === void 0 ? working.length : workingIndexByKey.get(anchor.key);
      if (anchorIndex === void 0) {
        throw new PluginUIReconcileError("Plugin UI keyed anchor became inconsistent");
      }
      if (foundIndex === void 0) {
        append({ type: "insert_child", parent_key: parentKey, child_index: anchorIndex, node: wanted });
        working.splice(anchorIndex, 0, wanted);
        refreshWorkingIndexes(anchorIndex);
        continue;
      }
      if (stableDesiredIndexes.has(desiredIndex)) continue;
      const toIndex = foundIndex < anchorIndex ? anchorIndex - 1 : anchorIndex;
      if (foundIndex === toIndex) continue;
      const found = working[foundIndex];
      ensureCanvasStable(found, "moved");
      append({
        type: "move_child",
        parent_key: parentKey,
        child_key: found.key,
        from_index: foundIndex,
        to_index: toIndex
      });
      working.splice(foundIndex, 1);
      working.splice(toIndex, 0, found);
      refreshWorkingIndexes(Math.min(foundIndex, toIndex));
    }
  }
  function estimateKeyedStructuralOperations(current, next) {
    const currentIndexes = keyedChildIndexes(current);
    const currentByKey = keyedChildren(current);
    const nextByKey = keyedChildren(next);
    const retainedIndexes = [];
    let inserted = 0;
    for (const child of next) {
      if (typeof child === "string") continue;
      const currentIndex = currentIndexes.get(child.key);
      const currentChild = currentByKey.get(child.key);
      if (currentIndex === void 0 || currentChild?.tag !== child.tag) inserted += 1;
      else retainedIndexes.push(currentIndex);
    }
    let removed = 0;
    for (const [key, child] of currentByKey) {
      const nextChild = nextByKey.get(key);
      if (!nextChild || nextChild.tag !== child.tag) removed += 1;
    }
    return inserted + removed + retainedIndexes.length - longestIncreasingSubsequenceIndexes(retainedIndexes).length;
  }
  function keyedChildren(children) {
    const keyed = /* @__PURE__ */ new Map();
    for (const child of children) {
      if (typeof child !== "string") keyed.set(child.key, child);
    }
    return keyed;
  }
  function longestIncreasingSubsequenceIndexes(values) {
    const predecessors = new Array(values.length).fill(-1);
    const tailIndexes = [];
    for (let index = 0; index < values.length; index += 1) {
      const value = values[index];
      let low = 0;
      let high = tailIndexes.length;
      while (low < high) {
        const middle = low + high >>> 1;
        if ((values[tailIndexes[middle]] ?? Infinity) < value) low = middle + 1;
        else high = middle;
      }
      if (low > 0) predecessors[index] = tailIndexes[low - 1] ?? -1;
      tailIndexes[low] = index;
    }
    const indexes = new Array(tailIndexes.length);
    let cursor = tailIndexes[tailIndexes.length - 1] ?? -1;
    for (let index = indexes.length - 1; index >= 0; index -= 1) {
      indexes[index] = cursor;
      cursor = predecessors[cursor] ?? -1;
    }
    return indexes;
  }
  function reconcileAttributes(current, next, controlEditRevisions, append) {
    const left = current.attributes ?? {};
    const right = next.attributes ?? {};
    const set = {};
    const remove = [];
    for (const [name, value] of Object.entries(right)) {
      if (!isEditableControlAttribute(current.tag, name) && left[name] !== value) set[name] = value;
    }
    for (const name of Object.keys(left)) {
      if (!isEditableControlAttribute(current.tag, name) && !(name in right)) remove.push(name);
    }
    if (Object.keys(set).length > 0 || remove.length > 0) {
      append({ type: "patch_attributes", target_key: current.key, set, remove });
    }
    const valueChanged = editableValueTags.has(current.tag) && left.value !== right.value;
    const checkedChanged = current.tag === "input" && left.checked !== right.checked;
    if (valueChanged || checkedChanged) {
      append({
        type: "patch_control",
        target_key: current.key,
        edit_revision: controlEditRevisions?.get(current.key) ?? 0,
        ...valueChanged ? { value: right.value === void 0 ? null : String(right.value) } : {},
        ...checkedChanged ? { checked: right.checked === void 0 ? null : Boolean(right.checked) } : {}
      });
    }
  }
  function isEditableControlAttribute(tag, name) {
    const normalized = name.toLowerCase();
    return normalized === "value" && editableValueTags.has(tag) || normalized === "checked" && tag === "input";
  }

  // packages/redevplugin-ui/src/surface.ts
  var opaquePluginBridgeGlobalKey = "__redevpluginWorkerBridge";
  var maxPendingPluginBridgeRequests = 256;
  var maxPluginBridgeMessageBytes = 256 * 1024;
  var maxOpaqueSurfaceLazyBytes = 32 * 1024 * 1024;
  var pluginBridgeErrorCodeSet = new Set(pluginBridgeErrorCodes);
  var hostCapabilityIDPattern = new RegExp("^[A-Za-z0-9][A-Za-z0-9._-]*$");
  var canonicalSemverPattern = new RegExp("^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-(?:(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\\+[0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*)?$");
  var lowercaseSHA256Pattern = new RegExp("^[0-9a-f]{64}$");
  var businessErrorCodePattern = new RegExp("^[A-Z][A-Z0-9_]*$");
  var PluginBridgeClient = class {
    surfaceHandle;
    timeoutMs;
    #nextID = 1;
    #port;
    #pending = /* @__PURE__ */ new Map();
    #actionHandlers = /* @__PURE__ */ new Map();
    #canvasInputHandlers = /* @__PURE__ */ new Map();
    #lifecycleHandlers = /* @__PURE__ */ new Set();
    #ready = false;
    #readyPromise;
    #resolveReady;
    #rejectReady;
    #lifecycleState = "active";
    #handlingLifecycle = false;
    #renderRevision = 0;
    #committedTree;
    #pendingRender;
    #renderLoop;
    #controlEditRevisions = /* @__PURE__ */ new Map();
    #pendingStreamDeliveries = /* @__PURE__ */ new Map();
    #onMessage = (event) => {
      void this.#handleMessage(event);
    };
    constructor(options = {}) {
      const claimed = options.port ? { port: options.port, surfaceHandle: normalizeSurfaceHandle(options.surfaceHandle) } : claimOpaquePluginBridge();
      this.surfaceHandle = claimed.surfaceHandle;
      this.timeoutMs = normalizeTimeout(options.timeoutMs);
      this.#port = claimed.port;
      this.#readyPromise = new Promise((resolve, reject) => {
        this.#resolveReady = resolve;
        this.#rejectReady = reject;
      });
      void this.#readyPromise.catch(() => void 0);
      this.#port.addEventListener("message", this.#onMessage);
      this.#port.start();
    }
    ready() {
      this.#assertActive();
      return this.#ready ? Promise.resolve() : this.#readyPromise;
    }
    call(method, params) {
      this.#assertActive();
      if (!validMethod(method)) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin bridge method and params are invalid");
      }
      let normalizedParams;
      try {
        normalizedParams = params === void 0 ? void 0 : normalizePluginJSONObject(params);
      } catch {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin bridge params must be canonical JSON");
      }
      const id = this.#requestID("rpc");
      const request = normalizedParams === void 0 ? { id, method } : { id, method, params: normalizedParams };
      return this.#request(id, {
        type: "redevplugin.bridge.call",
        request
      }, { mutationOutcomeOnTimeout: "unknown" });
    }
    readStream(streamHandle) {
      this.#assertActive();
      if (!validOpaqueHandle(streamHandle, "stream")) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin stream handle is invalid");
      }
      return this.#readStream(streamHandle);
    }
    async #readStream(streamHandle) {
      const pending = this.#pendingStreamDeliveries.get(streamHandle);
      if (pending) {
        await this.#acknowledgeStream(streamHandle, pending.deliveryID);
        this.#pendingStreamDeliveries.delete(streamHandle);
        return pending.result;
      }
      const id = this.#requestID("stream");
      const privateResult = await this.#request(id, {
        type: "redevplugin.bridge.stream.read",
        id,
        stream_handle: streamHandle
      });
      const { delivery_id: deliveryID, ...result } = privateResult;
      if (!deliveryID) return result;
      this.#pendingStreamDeliveries.set(streamHandle, { deliveryID, result });
      await this.#acknowledgeStream(streamHandle, deliveryID);
      this.#pendingStreamDeliveries.delete(streamHandle);
      return result;
    }
    async #acknowledgeStream(streamHandle, deliveryID) {
      const id = this.#requestID("stream_ack");
      await this.#request(id, {
        type: "redevplugin.bridge.stream.ack",
        id,
        stream_handle: streamHandle,
        delivery_id: deliveryID
      }, { mutationOutcomeOnTimeout: "unknown" });
    }
    cancelOperation(operationID, reason) {
      this.#assertActive();
      if (!validOpaqueHandle(operationID, "operation") || reason !== void 0 && (typeof reason !== "string" || reason.length > 256)) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin operation cancellation is invalid");
      }
      const id = this.#requestID("operation");
      return this.#request(id, removeUndefined({
        type: "redevplugin.bridge.operation.cancel",
        id,
        operation_id: operationID,
        reason
      }), { mutationOutcomeOnTimeout: "unknown" });
    }
    render(tree) {
      this.#assertActive();
      let validated;
      try {
        validated = validatePluginUITree(tree);
      } catch (error) {
        throw new PluginBridgeError(
          "PLUGIN_UI_PROTOCOL_VIOLATION",
          error instanceof Error ? error.message : "Plugin UI tree is invalid"
        );
      }
      return new Promise((resolve, reject) => {
        const waiters = this.#pendingRender?.waiters ?? [];
        waiters.push({ resolve, reject });
        this.#pendingRender = { tree: validated, waiters };
        this.#startRenderLoop();
      });
    }
    openCanvas(canvasId) {
      this.#assertActive();
      if (!validUIIdentifier(canvasId)) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin canvas identifier is invalid");
      }
      const id = this.#requestID("canvas");
      return this.#request(id, {
        type: "redevplugin.ui.canvas.open",
        id,
        canvas_id: canvasId
      }, { kind: "canvas", identifier: canvasId });
    }
    updateCanvasAccessibility(canvasId, state2) {
      this.#assertActive();
      if (!validUIIdentifier(canvasId) || !validCanvasAccessibilityState(state2)) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin canvas accessibility state is invalid");
      }
      const id = this.#requestID("canvas");
      return this.#request(id, {
        type: "redevplugin.ui.canvas.accessibility",
        id,
        canvas_id: canvasId,
        label: state2.label,
        description: state2.description
      });
    }
    loadImageAsset(assetId) {
      this.#assertActive();
      if (!validUIIdentifier(assetId)) {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin image asset identifier is invalid");
      }
      const id = this.#requestID("asset");
      return this.#request(id, {
        type: "redevplugin.ui.asset.image.open",
        id,
        asset_id: assetId
      }, { kind: "asset", identifier: assetId });
    }
    onAction(action, handler) {
      this.#assertActive();
      if (!validActionID(action) || typeof handler !== "function") {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin action subscription is invalid");
      }
      const handlers = this.#actionHandlers.get(action) ?? /* @__PURE__ */ new Set();
      handlers.add(handler);
      this.#actionHandlers.set(action, handlers);
      return () => {
        handlers.delete(handler);
        if (handlers.size === 0) this.#actionHandlers.delete(action);
      };
    }
    onCanvasInput(canvasId, handler) {
      this.#assertActive();
      if (!validUIIdentifier(canvasId) || typeof handler !== "function") {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin canvas input subscription is invalid");
      }
      const handlers = this.#canvasInputHandlers.get(canvasId) ?? /* @__PURE__ */ new Set();
      handlers.add(handler);
      this.#canvasInputHandlers.set(canvasId, handlers);
      return () => {
        handlers.delete(handler);
        if (handlers.size === 0) this.#canvasInputHandlers.delete(canvasId);
      };
    }
    onLifecycle(handler) {
      this.#assertActive();
      this.#lifecycleHandlers.add(handler);
      return () => {
        this.#lifecycleHandlers.delete(handler);
      };
    }
    dispose() {
      if (this.#lifecycleState === "disposed") return;
      this.#lifecycleState = "disposed";
      const disposedError = new PluginBridgeError("PLUGIN_BRIDGE_DISPOSED", "Plugin bridge client is disposed");
      if (!this.#ready) this.#rejectReady(disposedError);
      this.#port.removeEventListener("message", this.#onMessage);
      for (const [id, pending] of this.#pending) {
        clearTimeout(pending.timer);
        pending.reject(new PluginBridgeError("PLUGIN_BRIDGE_DISPOSED", `Plugin bridge request ${id} was disposed`));
      }
      this.#pending.clear();
      this.#pendingStreamDeliveries.clear();
      this.#actionHandlers.clear();
      this.#canvasInputHandlers.clear();
      this.#lifecycleHandlers.clear();
      for (const waiter of this.#pendingRender?.waiters ?? []) waiter.reject(disposedError);
      this.#pendingRender = void 0;
      this.#controlEditRevisions.clear();
      this.#port.close();
    }
    async #drainRenders() {
      while (this.#pendingRender && this.#acceptsPluginWork()) {
        const pending = this.#pendingRender;
        this.#pendingRender = void 0;
        const id = this.#requestID("render");
        const nextRevision = this.#renderRevision + 1;
        try {
          if (!this.#committedTree) {
            await this.#request(id, {
              type: "redevplugin.ui.mount",
              id,
              revision: 1,
              tree: pending.tree
            });
          } else {
            const operations = reconcilePluginUITrees(this.#committedTree, pending.tree, {
              controlEditRevisions: this.#controlEditRevisions
            });
            if (operations.length > 0) {
              await this.#request(id, {
                type: "redevplugin.ui.patch",
                id,
                base_revision: this.#renderRevision,
                revision: nextRevision,
                operations
              });
              this.#renderRevision = nextRevision;
            }
          }
          this.#committedTree = pending.tree;
          if (this.#renderRevision === 0) this.#renderRevision = 1;
          for (const waiter of pending.waiters) waiter.resolve();
        } catch (error) {
          const bridgeError = error instanceof PluginUIReconcileError ? new PluginBridgeError("PLUGIN_UI_PROTOCOL_VIOLATION", error.message) : error;
          for (const waiter of pending.waiters) waiter.reject(bridgeError);
          const queued = this.#pendingRender;
          for (const waiter of queued?.waiters ?? []) waiter.reject(bridgeError);
          this.#pendingRender = void 0;
          throw bridgeError;
        }
      }
      if (this.#pendingRender) {
        const error = new PluginBridgeError("PLUGIN_BRIDGE_DISPOSED", "Plugin UI cannot render after quiescing starts");
        for (const waiter of this.#pendingRender.waiters) waiter.reject(error);
        this.#pendingRender = void 0;
      }
    }
    #startRenderLoop() {
      if (this.#renderLoop) return;
      this.#renderLoop = this.#drainRenders().catch(() => void 0).finally(() => {
        this.#renderLoop = void 0;
        if (this.#pendingRender) this.#startRenderLoop();
      });
    }
    #request(id, message, options = {}) {
      let normalizedMessage;
      try {
        normalizedMessage = normalizePluginJSONObject(message);
      } catch {
        throw new PluginBridgeError("PLUGIN_INVALID_REQUEST", "Plugin bridge request must be canonical JSON");
      }
      if (new TextEncoder().encode(JSON.stringify(normalizedMessage)).byteLength > maxPluginBridgeMessageBytes) {
        throw new PluginBridgeError("PLUGIN_JSON_LIMIT_EXCEEDED", "Plugin bridge request exceeds the message size limit");
      }
      if (this.#pending.size >= maxPendingPluginBridgeRequests) {
        throw new PluginBridgeError("PLUGIN_JSON_LIMIT_EXCEEDED", "Plugin bridge has too many pending requests");
      }
      const result = new Promise((resolve, reject) => {
        const timer = setTimeout(() => {
          if (!this.#pending.delete(id)) return;
          try {
            this.#port.postMessage({ type: "redevplugin.bridge.cancel", id });
          } catch {
          }
          reject(new PluginBridgeError(
            "PLUGIN_BRIDGE_TIMEOUT",
            `Plugin bridge request ${id} timed out`,
            void 0,
            void 0,
            options.mutationOutcomeOnTimeout
          ));
        }, this.timeoutMs);
        this.#pending.set(id, {
          resolve: (value) => resolve(value),
          reject,
          timer,
          kind: options.kind ?? "json",
          identifier: options.identifier
        });
      });
      try {
        this.#port.postMessage(normalizedMessage);
      } catch {
        const pending = this.#pending.get(id);
        if (pending) {
          this.#pending.delete(id);
          clearTimeout(pending.timer);
          pending.reject(new PluginBridgeError("PLUGIN_BRIDGE_DISPOSED", `Plugin bridge request ${id} could not be posted`));
        }
      }
      return result;
    }
    async #handleMessage(event) {
      if (this.#lifecycleState === "disposed") return;
      const data = event.data;
      if (isCanvasReadyCandidate(data)) {
        const pending = this.#pending.get(data.id);
        if (!pending) return;
        this.#pending.delete(data.id);
        clearTimeout(pending.timer);
        if (pending.kind !== "canvas" || pending.identifier !== data.canvas_id || !isCanvasReadyMessage(data)) {
          pending.reject(new PluginBridgeError("PLUGIN_CONTRACT_MISMATCH", `Plugin canvas response ${data.id} is invalid`));
          return;
        }
        pending.resolve({
          canvas: data.canvas,
          canvasId: data.canvas_id,
          cssWidth: data.css_width,
          cssHeight: data.css_height,
          devicePixelRatio: data.device_pixel_ratio
        });
        return;
      }
      if (isImageReadyCandidate(data)) {
        const pending = this.#pending.get(data.id);
        if (!pending) return;
        this.#pending.delete(data.id);
        clearTimeout(pending.timer);
        if (pending.kind !== "asset" || pending.identifier !== data.asset_id || !isImageReadyMessage(data)) {
          pending.reject(new PluginBridgeError("PLUGIN_CONTRACT_MISMATCH", `Plugin image response ${data.id} is invalid`));
          return;
        }
        pending.resolve(data.image);
        return;
      }
      if (!messageWithinLimit(data)) return;
      if (isBridgeResponseCandidate(data)) {
        const pending = this.#pending.get(data.id);
        if (!pending) return;
        this.#pending.delete(data.id);
        clearTimeout(pending.timer);
        if (!isBridgeResponse(data)) {
          pending.reject(new PluginBridgeError("PLUGIN_CONTRACT_MISMATCH", `Plugin bridge response ${data.id} is invalid`));
          return;
        }
        if (data.ok && pending.kind !== "json") {
          pending.reject(new PluginBridgeError("PLUGIN_CONTRACT_MISMATCH", `Plugin transfer response ${data.id} is invalid`));
        } else if (data.ok) pending.resolve(data.data);
        else pending.reject(new PluginBridgeError(data.error_code, data.error, void 0, data.error_details, data.mutation_outcome));
        return;
      }
      if (isLifecycleMessage(data)) {
        if (data.event.type === "ready" && !this.#ready) {
          this.#ready = true;
          this.#resolveReady();
        }
        if (data.quiesce_id) this.#lifecycleState = "quiescing";
        this.#handlingLifecycle = true;
        await Promise.allSettled(Array.from(this.#lifecycleHandlers, async (handler) => {
          try {
            await handler(data.event);
          } catch {
          }
        }));
        this.#handlingLifecycle = false;
        if (data.quiesce_id) {
          this.#port.postMessage({
            type: "redevplugin.bridge.lifecycle_ack",
            quiesce_id: data.quiesce_id
          });
          this.#lifecycleState = "quiesced";
        }
        if (data.event.type === "dispose" && !data.quiesce_id) this.dispose();
        return;
      }
      if (isActionMessage(data)) {
        this.#controlEditRevisions.set(data.target_key, data.edit_revision);
        const action = publicActionEvent(data);
        for (const handler of this.#actionHandlers.get(data.action) ?? []) handler(action);
        return;
      }
      const canvasInput = publicCanvasInputMessage(data);
      if (canvasInput) {
        for (const handler of this.#canvasInputHandlers.get(canvasInput.canvasId) ?? []) handler(canvasInput.event);
      }
    }
    #requestID(prefix) {
      return `${prefix}_${this.#nextID++}`;
    }
    #assertActive() {
      if (!this.#acceptsPluginWork()) {
        throw new PluginBridgeError("PLUGIN_BRIDGE_DISPOSED", "Plugin bridge client is disposed");
      }
    }
    #acceptsPluginWork() {
      return this.#lifecycleState === "active" || this.#lifecycleState === "quiescing" && this.#handlingLifecycle;
    }
  };
  var pluginSurfaceHostConstructorToken = Symbol("redevplugin.surface-host.constructor");
  function claimOpaquePluginBridge() {
    const value = globalThis[opaquePluginBridgeGlobalKey];
    if (!isRecord(value) || typeof value.claim !== "function") {
      throw new PluginBridgeError("PLUGIN_BRIDGE_HANDSHAKE_REQUIRED", "Opaque plugin worker bridge is unavailable");
    }
    const claimed = value.claim();
    if (!claimed || !isMessagePortLike(claimed.port) || !validOpaqueHandle(claimed.surfaceHandle, "surface")) {
      throw new PluginBridgeError("PLUGIN_BRIDGE_HANDSHAKE_REQUIRED", "Opaque plugin worker bridge was already claimed");
    }
    return claimed;
  }
  function normalizeSurfaceHandle(value) {
    if (!validOpaqueHandle(value, "surface")) {
      throw new PluginBridgeError("PLUGIN_BRIDGE_HANDSHAKE_REQUIRED", "A valid surface handle is required with an explicit bridge port");
    }
    return value;
  }
  var deniedPluginPermissionsPolicy = [
    "accelerometer 'none'",
    "autoplay 'none'",
    "bluetooth 'none'",
    "camera 'none'",
    "clipboard-read 'none'",
    "clipboard-write 'none'",
    "display-capture 'none'",
    "encrypted-media 'none'",
    "fullscreen 'none'",
    "gamepad 'none'",
    "geolocation 'none'",
    "gyroscope 'none'",
    "hid 'none'",
    "magnetometer 'none'",
    "microphone 'none'",
    "midi 'none'",
    "payment 'none'",
    "picture-in-picture 'none'",
    "publickey-credentials-get 'none'",
    "screen-wake-lock 'none'",
    "serial 'none'",
    "usb 'none'",
    "xr-spatial-tracking 'none'"
  ].join("; ");
  function isBridgeResponseCandidate(value) {
    return isRecord(value) && value.type === "redevplugin.bridge.response" && typeof value.id === "string";
  }
  function isBridgeResponse(value) {
    if (!isBridgeResponseCandidate(value) || !validBridgeRequestID(value.id)) return false;
    if (value.ok === true) return Object.keys(value).every((key) => ["type", "id", "ok", "data"].includes(key));
    if (value.ok !== false || typeof value.error_code !== "string" || !pluginBridgeErrorCodeSet.has(value.error_code) || typeof value.error !== "string" || value.error.length > 4096 || !Object.keys(value).every((key) => ["type", "id", "ok", "error_code", "error", "error_details", "mutation_outcome"].includes(key)) || value.mutation_outcome !== void 0 && value.mutation_outcome !== "not_committed" && value.mutation_outcome !== "unknown") {
      return false;
    }
    if (value.error_code === "PLUGIN_CAPABILITY_ERROR") return isCapabilityBusinessErrorDetails(value.error_details);
    if (value.error_code === "PLUGIN_WORKER_ERROR") return isWorkerErrorDetails(value.error_details);
    if (value.error_details === void 0) return true;
    try {
      return Object.keys(normalizePluginJSONObject(value.error_details)).length <= 8;
    } catch {
      return false;
    }
  }
  function validCanvasAccessibilityState(value) {
    return hasExactKeys(value, ["label", "description"]) && typeof value.label === "string" && value.label.length > 0 && value.label.length <= 256 && typeof value.description === "string" && value.description.length <= 1024;
  }
  function isWorkerErrorDetails(value) {
    return hasExactKeys(value, ["worker_error_code", "worker_error_message", "worker_error_origin"]) && typeof value.worker_error_code === "string" && businessErrorCodePattern.test(value.worker_error_code) && typeof value.worker_error_message === "string" && value.worker_error_message.length > 0 && value.worker_error_message.length <= 4096 && (value.worker_error_origin === "runtime" || value.worker_error_origin === "hostcall" || value.worker_error_origin === "plugin");
  }
  function isCapabilityBusinessErrorDetails(value) {
    if (!hasAllowedKeys(value, [
      "capability_id",
      "capability_version",
      "detail_schema_sha256",
      "business_error_code",
      "business_error_details"
    ])) return false;
    if (typeof value.capability_id !== "string" || !hostCapabilityIDPattern.test(value.capability_id) || typeof value.capability_version !== "string" || !canonicalSemverPattern.test(value.capability_version) || typeof value.detail_schema_sha256 !== "string" || !lowercaseSHA256Pattern.test(value.detail_schema_sha256) || typeof value.business_error_code !== "string" || !businessErrorCodePattern.test(value.business_error_code)) {
      return false;
    }
    if (value.business_error_details === void 0) return true;
    try {
      normalizePluginJSONObject(value.business_error_details);
      return true;
    } catch {
      return false;
    }
  }
  function isLifecycleMessage(value) {
    return hasAllowedKeys(value, ["type", "event", "quiesce_id"]) && value.type === "redevplugin.bridge.lifecycle" && hasExactKeys(value.event, ["type"]) && (value.event.type === "ready" || value.event.type === "visible" || value.event.type === "hidden" || value.event.type === "dispose") && (value.quiesce_id === void 0 || value.event.type === "dispose" && validOpaqueHandle(value.quiesce_id, "quiesce"));
  }
  function isActionMessage(value) {
    return hasAllowedKeys(value, ["type", "action", "event", "target_key", "edit_revision", "is_composing", "value", "checked", "form_data"]) && value.type === "redevplugin.ui.action" && validActionID(value.action) && (value.event === "click" || value.event === "input" || value.event === "change" || value.event === "submit" || value.event === "escape") && validUIIdentifier(value.target_key) && Number.isSafeInteger(value.edit_revision) && Number(value.edit_revision) >= 0 && typeof value.is_composing === "boolean" && (value.value == null || typeof value.value === "string" && value.value.length <= 65536) && (value.checked == null || typeof value.checked === "boolean") && (value.form_data == null || isRecord(value.form_data) && Object.entries(value.form_data).every(([key, item]) => validActionID(key) && typeof item === "string" && item.length <= 65536));
  }
  function publicActionEvent(value) {
    return removeUndefined({
      action: value.action,
      event: value.event,
      targetKey: value.target_key,
      editRevision: value.edit_revision,
      isComposing: value.is_composing,
      value: value.value,
      checked: value.checked,
      form_data: value.form_data
    });
  }
  function isCanvasReadyCandidate(value) {
    return isRecord(value) && value.type === "redevplugin.ui.canvas.ready" && typeof value.id === "string" && typeof value.canvas_id === "string";
  }
  function isCanvasReadyMessage(value) {
    return hasExactKeys(value, ["type", "id", "canvas_id", "canvas", "css_width", "css_height", "device_pixel_ratio"]) && value.type === "redevplugin.ui.canvas.ready" && validBridgeRequestID(value.id, "canvas") && validUIIdentifier(value.canvas_id) && isOffscreenCanvasLike(value.canvas) && validSurfaceDimension(value.css_width) && validSurfaceDimension(value.css_height) && validDevicePixelRatio(value.device_pixel_ratio);
  }
  function isImageReadyCandidate(value) {
    return isRecord(value) && value.type === "redevplugin.ui.asset.image.ready" && typeof value.id === "string" && typeof value.asset_id === "string";
  }
  function isImageReadyMessage(value) {
    return hasExactKeys(value, ["type", "id", "asset_id", "image", "width", "height"]) && value.type === "redevplugin.ui.asset.image.ready" && validBridgeRequestID(value.id, "asset") && validUIIdentifier(value.asset_id) && isImageBitmapLike(value.image) && Number.isInteger(value.width) && Number(value.width) > 0 && Number(value.width) <= opaqueSurfaceRenderLimits.max_image_dimension && Number.isInteger(value.height) && Number(value.height) > 0 && Number(value.height) <= opaqueSurfaceRenderLimits.max_image_dimension && value.image.width === value.width && value.image.height === value.height;
  }
  function publicCanvasInputMessage(value) {
    if (!hasExactKeys(value, ["type", "canvas_id", "event"]) || value.type !== "redevplugin.ui.canvas.input" || !validUIIdentifier(value.canvas_id) || !isRecord(value.event)) return void 0;
    const event = value.event;
    if (hasExactKeys(event, ["type"]) && (event.type === "focus" || event.type === "blur")) {
      return { canvasId: value.canvas_id, event: { type: event.type } };
    }
    if (hasExactKeys(event, ["type", "css_width", "css_height", "device_pixel_ratio"]) && event.type === "resize" && validSurfaceDimension(event.css_width) && validSurfaceDimension(event.css_height) && validDevicePixelRatio(event.device_pixel_ratio)) {
      return {
        canvasId: value.canvas_id,
        event: { type: "resize", cssWidth: event.css_width, cssHeight: event.css_height, devicePixelRatio: event.device_pixel_ratio }
      };
    }
    if (hasExactKeys(event, ["type", "event", "code", "key", "repeat", "alt_key", "ctrl_key", "meta_key", "shift_key"]) && event.type === "key" && (event.event === "keydown" || event.event === "keyup") && typeof event.code === "string" && event.code.length <= 64 && typeof event.key === "string" && event.key.length <= 64 && typeof event.repeat === "boolean" && typeof event.alt_key === "boolean" && typeof event.ctrl_key === "boolean" && typeof event.meta_key === "boolean" && typeof event.shift_key === "boolean") {
      return {
        canvasId: value.canvas_id,
        event: {
          type: "key",
          event: event.event,
          code: event.code,
          key: event.key,
          repeat: event.repeat,
          altKey: event.alt_key,
          ctrlKey: event.ctrl_key,
          metaKey: event.meta_key,
          shiftKey: event.shift_key
        }
      };
    }
    if (hasExactKeys(event, ["type", "event", "pointer_id", "pointer_type", "buttons", "button", "x", "y", "pressure"]) && event.type === "pointer" && ["pointerdown", "pointermove", "pointerup", "pointercancel"].includes(String(event.event)) && Number.isInteger(event.pointer_id) && Number(event.pointer_id) >= 0 && ["mouse", "pen", "touch", "unknown"].includes(String(event.pointer_type)) && Number.isInteger(event.buttons) && Number(event.buttons) >= 0 && Number(event.buttons) <= 31 && Number.isInteger(event.button) && Number(event.button) >= -1 && Number(event.button) <= 4 && validCanvasCoordinate(event.x) && validCanvasCoordinate(event.y) && typeof event.pressure === "number" && Number.isFinite(event.pressure) && event.pressure >= 0 && event.pressure <= 1) {
      return {
        canvasId: value.canvas_id,
        event: {
          type: "pointer",
          event: event.event,
          pointerId: Number(event.pointer_id),
          pointerType: event.pointer_type,
          buttons: Number(event.buttons),
          button: Number(event.button),
          x: event.x,
          y: event.y,
          pressure: event.pressure
        }
      };
    }
    return void 0;
  }
  function isOffscreenCanvasLike(value) {
    return isRecord(value) && Number.isInteger(value.width) && Number(value.width) > 0 && Number(value.width) <= opaqueSurfaceRenderLimits.max_canvas_dimension && Number.isInteger(value.height) && Number(value.height) > 0 && Number(value.height) <= opaqueSurfaceRenderLimits.max_canvas_dimension && typeof value.getContext === "function";
  }
  function isImageBitmapLike(value) {
    return isRecord(value) && Number.isInteger(value.width) && Number(value.width) > 0 && Number(value.width) <= opaqueSurfaceRenderLimits.max_image_dimension && Number.isInteger(value.height) && Number(value.height) > 0 && Number(value.height) <= opaqueSurfaceRenderLimits.max_image_dimension && typeof value.close === "function";
  }
  function validSurfaceDimension(value) {
    return typeof value === "number" && Number.isFinite(value) && value > 0 && value <= opaqueSurfaceRenderLimits.max_canvas_dimension;
  }
  function validDevicePixelRatio(value) {
    return typeof value === "number" && Number.isFinite(value) && value >= 0.5 && value <= 4;
  }
  function validCanvasCoordinate(value) {
    return typeof value === "number" && Number.isFinite(value) && value >= -16384 && value <= 32768;
  }
  function isMessagePortLike(value) {
    return isRecord(value) && typeof value.postMessage === "function" && typeof value.addEventListener === "function" && typeof value.removeEventListener === "function" && typeof value.start === "function" && typeof value.close === "function";
  }
  var pluginMethodPattern = new RegExp("^[-A-Za-z0-9._:]{1,256}$");
  var pluginActionPattern = new RegExp("^[-A-Za-z0-9._:]{1,128}$");
  var pluginUIIdentifierPattern = new RegExp("^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$");
  var opaqueHandlePattern2 = new RegExp("^[-A-Za-z0-9_]{8,160}$");
  var bridgeRequestIDPattern = /^(rpc|stream|stream_ack|render|operation|canvas|asset)_([1-9][0-9]{0,15})$/;
  function validBridgeRequestID(value, expectedKind) {
    if (typeof value !== "string") return false;
    const match = bridgeRequestIDPattern.exec(value);
    if (!match || expectedKind && match[1] !== expectedKind) return false;
    return Number.isSafeInteger(Number(match[2]));
  }
  function validMethod(value) {
    return typeof value === "string" && pluginMethodPattern.test(value);
  }
  function validActionID(value) {
    return typeof value === "string" && pluginActionPattern.test(value);
  }
  function validUIIdentifier(value) {
    return typeof value === "string" && pluginUIIdentifierPattern.test(value);
  }
  function validOpaqueHandle(value, prefix) {
    return typeof value === "string" && value.startsWith(`${prefix}_`) && opaqueHandlePattern2.test(value);
  }
  function messageWithinLimit(value) {
    try {
      const normalized = normalizePluginJSONValue(value);
      return new TextEncoder().encode(JSON.stringify(normalized)).byteLength <= maxPluginBridgeMessageBytes;
    } catch {
      return false;
    }
  }
  function normalizePluginJSONObject(value) {
    const normalized = normalizePluginJSONValue(value);
    if (normalized === null || Array.isArray(normalized) || typeof normalized !== "object") {
      throw new TypeError("value must be a JSON object");
    }
    return normalized;
  }
  function normalizePluginJSONValue(value, depth = 0, state2 = { nodes: 0, seen: /* @__PURE__ */ new Set() }) {
    state2.nodes += 1;
    if (state2.nodes > 4096 || depth > 64) throw new TypeError("JSON value exceeds structural limits");
    if (value === null || typeof value === "string" || typeof value === "boolean") return value;
    if (typeof value === "number") {
      if (!Number.isFinite(value)) throw new TypeError("JSON numbers must be finite");
      return value;
    }
    if (typeof value !== "object" || state2.seen.has(value)) throw new TypeError("value is not canonical JSON");
    state2.seen.add(value);
    try {
      if (Array.isArray(value)) {
        return value.map((item) => normalizePluginJSONValue(item, depth + 1, state2));
      }
      const prototype = Object.getPrototypeOf(value);
      if (prototype !== Object.prototype && prototype !== null) throw new TypeError("JSON objects must be plain records");
      const result = {};
      for (const key of Reflect.ownKeys(value)) {
        if (typeof key !== "string") throw new TypeError("JSON object keys must be strings");
        if (prototypeSensitivePropertyNames.has(key)) throw new TypeError("JSON object keys must not alter object prototypes");
        const descriptor = Object.getOwnPropertyDescriptor(value, key);
        if (!descriptor?.enumerable || !("value" in descriptor)) throw new TypeError("JSON object fields must be enumerable data properties");
        result[key] = normalizePluginJSONValue(descriptor.value, depth + 1, state2);
      }
      return result;
    } finally {
      state2.seen.delete(value);
    }
  }
  var prototypeSensitivePropertyNames = /* @__PURE__ */ new Set(["__proto__", "constructor", "prototype"]);
  function normalizeTimeout(timeoutMs) {
    if (timeoutMs == null) return 3e4;
    if (!Number.isFinite(timeoutMs) || timeoutMs <= 0) throw new Error("timeoutMs must be a positive finite number");
    return timeoutMs;
  }
  function removeUndefined(value) {
    for (const key of Object.keys(value)) if (value[key] === void 0) delete value[key];
    return value;
  }

  // internal/scaffoldtemplate/plugin-worker.ts
  var bridge = new PluginBridgeClient({ timeoutMs: 2e4 });
  var state = {
    message: "Hello from the generated plugin",
    response: "Your WASM worker response will appear here.",
    status: "Connecting...",
    busy: false,
    error: false
  };
  bridge.onAction("echo-message", (event) => void echoMessage(event));
  void initialize();
  async function initialize() {
    await bridge.ready();
    state.status = "Ready";
    await render();
  }
  async function echoMessage(event) {
    if (state.busy) return;
    const message = String(event.form_data?.message ?? "").trim();
    if (!message) {
      state.status = "Enter a message first";
      state.error = true;
      await render();
      return;
    }
    state.message = message;
    state.busy = true;
    state.error = false;
    state.status = "Calling the sandboxed worker...";
    await render();
    try {
      const response = await bridge.call("worker.echo", { message });
      state.response = response.data.message;
      state.status = `Answered by ${response.data.worker_id}`;
    } catch (error) {
      state.response = error instanceof Error ? error.message : "The worker call failed.";
      state.status = "Worker unavailable";
      state.error = true;
    } finally {
      state.busy = false;
      await render();
    }
  }
  function render() {
    return bridge.render({
      type: "element",
      key: "plugin-root",
      tag: "main",
      attributes: { class: "plugin-surface" },
      children: [
        { type: "element", key: "plugin-eyebrow", tag: "p", attributes: { class: "eyebrow" }, children: ["Sandboxed plugin"] },
        { type: "element", key: "plugin-title", tag: "h1", children: ["__REDEVPLUGIN_DISPLAY_NAME__"] },
        { type: "element", key: "plugin-intro", tag: "p", attributes: { class: "intro" }, children: ["A minimal editable plugin with a TypeScript surface and Rust WASM worker."] },
        {
          type: "element",
          key: "echo-form",
          tag: "form",
          attributes: { class: "echo-form", "data-redevplugin-action": "echo-message" },
          children: [
            { type: "element", key: "message-label", tag: "label", attributes: { for: "message" }, children: ["Message"] },
            { type: "element", key: "message-input", tag: "input", attributes: { id: "message", name: "message", value: state.message, maxlength: 4096, disabled: state.busy, autocomplete: "off" } },
            { type: "element", key: "message-submit", tag: "button", attributes: { type: "submit", disabled: state.busy }, children: [state.busy ? "Sending..." : "Send to worker"] }
          ]
        },
        { type: "element", key: "plugin-status", tag: "p", attributes: { class: state.error ? "status error" : "status", role: "status" }, children: [state.status] },
        { type: "element", key: "worker-response", tag: "section", attributes: { class: "response", "aria-label": "Worker response" }, children: [
          { type: "element", key: "worker-response-label", tag: "span", children: ["Response"] },
          { type: "element", key: "worker-response-value", tag: "strong", children: [state.response] }
        ] }
      ]
    });
  }
})();
