package capabilitycontract

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

func GenerateTypeScript(contract Contract) ([]byte, error) {
	if err := Validate(contract); err != nil {
		return nil, err
	}
	var out strings.Builder
	out.WriteString("// Generated by ReDevPlugin. Do not edit.\n")
	out.WriteString("import {\n")
	out.WriteString("  callCapabilityOperation,\n")
	out.WriteString("  callCapabilityStream,\n")
	out.WriteString("  callCapabilitySync,\n")
	out.WriteString("  isCapabilityBusinessError,\n")
	out.WriteString("  type PluginBridgeClient,\n")
	out.WriteString("  type PluginBridgeError,\n")
	out.WriteString("  type PluginBridgeRequestOptions,\n")
	out.WriteString("  type PluginOperation,\n")
	out.WriteString("  type PluginStream,\n")
	out.WriteString("} from \"@floegence/redevplugin-ui/plugin\";\n\n")
	for _, method := range contract.Methods {
		requestType, err := schemaTypeScript(method.RequestSchema, "")
		if err != nil {
			return nil, err
		}
		responseType, err := schemaTypeScript(method.ResponseSchema, "")
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "export type %s = %s;\n\n", method.RequestTypeName, requestType)
		fmt.Fprintf(&out, "export type %s = %s;\n\n", method.ResponseTypeName, responseType)
		if method.Execution == "subscription" {
			eventType, err := schemaTypeScript(method.EventSchema, "")
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&out, "export type %s = %s;\n\n", method.EventTypeName, eventType)
		}
	}
	if len(contract.Errors) > 0 {
		baseName := strings.TrimSuffix(contract.ClientName, "Client")
		codes := make([]string, 0, len(contract.Errors))
		for _, item := range contract.Errors {
			codes = append(codes, fmt.Sprintf("%q", item.Code))
		}
		sort.Strings(codes)
		fmt.Fprintf(&out, "export type %sBusinessErrorCode = %s;\n\n", baseName, strings.Join(codes, " | "))
		fmt.Fprintf(&out, "export type %sBusinessErrorDetails =\n", baseName)
		for index, item := range contract.Errors {
			digest, err := DetailSchemaSHA256(item.DetailsSchema)
			if err != nil {
				return nil, err
			}
			if len(contract.Errors) == 1 {
				out.WriteString("  {\n")
			} else {
				out.WriteString("  | {\n")
			}
			fmt.Fprintf(&out, "    capability_id: %q;\n", contract.CapabilityID)
			fmt.Fprintf(&out, "    capability_version: %q;\n", contract.CapabilityVersion)
			fmt.Fprintf(&out, "    detail_schema_sha256: %q;\n", digest)
			fmt.Fprintf(&out, "    business_error_code: %q;\n", item.Code)
			if item.DetailsSchema == nil {
				if index == len(contract.Errors)-1 {
					out.WriteString("  };\n")
				} else {
					out.WriteString("  }\n")
				}
				continue
			}
			detailsType, err := schemaTypeScript(item.DetailsSchema, "    ")
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&out, "    business_error_details: %s;\n", detailsType)
			if index == len(contract.Errors)-1 {
				out.WriteString("  };\n")
			} else {
				out.WriteString("  }\n")
			}
		}
		out.WriteString("\n")
		fmt.Fprintf(&out, "export function is%sBusinessError(error: unknown): error is PluginBridgeError & { readonly details: %sBusinessErrorDetails } {\n", baseName, baseName)
		fmt.Fprintf(&out, "  return isCapabilityBusinessError(error, %q, %q, {\n", contract.CapabilityID, contract.CapabilityVersion)
		for _, item := range contract.Errors {
			digest, err := DetailSchemaSHA256(item.DetailsSchema)
			if err != nil {
				return nil, err
			}
			if item.DetailsSchema == nil {
				fmt.Fprintf(&out, "    %q: { detail_schema_sha256: %q, schema: null },\n", item.Code, digest)
				continue
			}
			detailsSchema, err := json.Marshal(item.DetailsSchema)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&out, "    %q: { detail_schema_sha256: %q, schema: %s },\n", item.Code, digest, detailsSchema)
		}
		out.WriteString("  });\n")
		out.WriteString("}\n\n")
	}
	for _, method := range contract.Methods {
		requestSchema, err := json.Marshal(method.RequestSchema)
		if err != nil {
			return nil, err
		}
		responseSchema, err := json.Marshal(method.ResponseSchema)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "const %sContract = Object.freeze({\n", method.ClientMethod)
		fmt.Fprintf(&out, "  method: %q,\n", method.Name)
		fmt.Fprintf(&out, "  effect: %q,\n", method.Effect)
		fmt.Fprintf(&out, "  execution: %q,\n", method.Execution)
		fmt.Fprintf(&out, "  requestSchema: %s,\n", requestSchema)
		fmt.Fprintf(&out, "  responseSchema: %s,\n", responseSchema)
		if method.Execution == "operation" {
			fmt.Fprintf(&out, "  cancelable: %t,\n", method.CancelPolicy.Cancelable)
		}
		if method.Execution == "subscription" {
			eventSchema, err := json.Marshal(method.EventSchema)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&out, "  eventTypeName: %q,\n", method.EventTypeName)
			fmt.Fprintf(&out, "  eventSchema: %s,\n", eventSchema)
		}
		out.WriteString("} as const);\n\n")
	}
	fmt.Fprintf(&out, "export class %s {\n", contract.ClientName)
	out.WriteString("  readonly #bridge: PluginBridgeClient;\n\n")
	out.WriteString("  constructor(bridge: PluginBridgeClient) {\n")
	out.WriteString("    this.#bridge = bridge;\n")
	out.WriteString("  }\n\n")
	for _, method := range contract.Methods {
		returnType := method.ResponseTypeName
		call := "callCapabilitySync"
		operationCancelable := true
		switch method.Execution {
		case "operation":
			returnType = "PluginOperation<" + method.ResponseTypeName + ">"
			call = "callCapabilityOperation"
			operationCancelable = method.CancelPolicy.Cancelable
			if !operationCancelable {
				returnType = "PluginOperation<" + method.ResponseTypeName + ", false>"
			}
		case "subscription":
			returnType = "PluginStream<" + method.ResponseTypeName + ", " + method.EventTypeName + ">"
			call = "callCapabilityStream"
		}
		fmt.Fprintf(&out, "  async %s(request: %s, options: PluginBridgeRequestOptions = {}): Promise<%s> {\n", method.ClientMethod, method.RequestTypeName, returnType)
		if method.Execution == "subscription" {
			fmt.Fprintf(&out, "    return %s<%s, %s, %s>(\n", call, method.RequestTypeName, method.ResponseTypeName, method.EventTypeName)
		} else if method.Execution == "operation" && !operationCancelable {
			fmt.Fprintf(&out, "    return %s<%s, %s, false>(\n", call, method.RequestTypeName, method.ResponseTypeName)
		} else {
			fmt.Fprintf(&out, "    return %s<%s, %s>(\n", call, method.RequestTypeName, method.ResponseTypeName)
		}
		out.WriteString("      this.#bridge,\n")
		fmt.Fprintf(&out, "      %sContract,\n", method.ClientMethod)
		out.WriteString("      request,\n")
		out.WriteString("      options,\n")
		out.WriteString("    );\n")
		out.WriteString("  }\n\n")
	}
	out.WriteString("}\n")
	return []byte(out.String()), nil
}
