// Generated by ReDevPlugin. Do not edit.
import {
  callCapabilityOperation,
  callCapabilityStream,
  callCapabilitySync,
  isCapabilityBusinessError,
  type PluginBridgeClient,
  type PluginBridgeError,
  type PluginBridgeRequestOptions,
  type PluginOperation,
  type PluginStream,
} from "@floegence/redevplugin-ui/plugin";

export type DocumentsListRequest = {
  workspace_id: string;
};

export type DocumentsListResponse = {
  documents: Array<{
    document_id: string;
    title: string;
  }>;
};

export type DocumentsArchiveRequest = {
  document_id: string;
};

export type DocumentsArchiveResponse = {
  accepted: boolean;
};

export type DocumentsWatchRequest = {
  workspace_id: string;
};

export type DocumentsWatchResponse = {
  watching: boolean;
};

export type DocumentsWatchEvent = {
  change: "created" | "updated" | "deleted";
  document_id: string;
};

export type ExampleDocumentsBusinessErrorCode = "DOCUMENT_NOT_FOUND";

export type ExampleDocumentsBusinessErrorDetails =
  {
    capability_id: "example.capability.documents";
    capability_version: "1.0.0";
    detail_schema_sha256: "e6bc44dc692e7cf12a96ace793c310f139a752e011a2f22bb85ed560f55ffc57";
    business_error_code: "DOCUMENT_NOT_FOUND";
    business_error_details: {
      document_id: string;
    };
  };

export function isExampleDocumentsBusinessError(error: unknown): error is PluginBridgeError & { readonly details: ExampleDocumentsBusinessErrorDetails } {
  return isCapabilityBusinessError(error, "example.capability.documents", "1.0.0", {
    "DOCUMENT_NOT_FOUND": { detail_schema_sha256: "e6bc44dc692e7cf12a96ace793c310f139a752e011a2f22bb85ed560f55ffc57", schema: {"additionalProperties":false,"properties":{"document_id":{"minLength":1,"type":"string"}},"required":["document_id"],"type":"object"} },
  });
}

const listContract = Object.freeze({
  method: "documents.list",
  effect: "read",
  execution: "sync",
  requestSchema: {"additionalProperties":false,"properties":{"workspace_id":{"minLength":1,"type":"string"}},"required":["workspace_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"documents":{"items":{"additionalProperties":false,"properties":{"document_id":{"minLength":1,"type":"string"},"title":{"minLength":1,"type":"string"}},"required":["document_id","title"],"type":"object"},"type":"array"}},"required":["documents"],"type":"object"},
} as const);

const archiveContract = Object.freeze({
  method: "documents.archive",
  effect: "write",
  execution: "operation",
  requestSchema: {"additionalProperties":false,"properties":{"document_id":{"minLength":1,"type":"string"}},"required":["document_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"accepted":{"type":"boolean"}},"required":["accepted"],"type":"object"},
  cancelable: true,
} as const);

const watchContract = Object.freeze({
  method: "documents.watch",
  effect: "read",
  execution: "subscription",
  requestSchema: {"additionalProperties":false,"properties":{"workspace_id":{"minLength":1,"type":"string"}},"required":["workspace_id"],"type":"object"},
  responseSchema: {"additionalProperties":false,"properties":{"watching":{"type":"boolean"}},"required":["watching"],"type":"object"},
  eventTypeName: "DocumentsWatchEvent",
  eventSchema: {"additionalProperties":false,"properties":{"change":{"enum":["created","updated","deleted"],"type":"string"},"document_id":{"minLength":1,"type":"string"}},"required":["document_id","change"],"type":"object"},
} as const);

export class ExampleDocumentsClient {
  readonly #bridge: PluginBridgeClient;

  constructor(bridge: PluginBridgeClient) {
    this.#bridge = bridge;
  }

  async list(request: DocumentsListRequest, options: PluginBridgeRequestOptions = {}): Promise<DocumentsListResponse> {
    return callCapabilitySync<DocumentsListRequest, DocumentsListResponse>(
      this.#bridge,
      listContract,
      request,
      options,
    );
  }

  async archive(request: DocumentsArchiveRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginOperation<DocumentsArchiveResponse>> {
    return callCapabilityOperation<DocumentsArchiveRequest, DocumentsArchiveResponse>(
      this.#bridge,
      archiveContract,
      request,
      options,
    );
  }

  async watch(request: DocumentsWatchRequest, options: PluginBridgeRequestOptions = {}): Promise<PluginStream<DocumentsWatchResponse, DocumentsWatchEvent>> {
    return callCapabilityStream<DocumentsWatchRequest, DocumentsWatchResponse, DocumentsWatchEvent>(
      this.#bridge,
      watchContract,
      request,
      options,
    );
  }

}
