// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

export const pluginUIProtocolVersion = "plugin-ui-v2" as const;
export const pluginHostProtocolVersion = "plugin-host-v2" as const;
export const bridgeSchemaVersion = "bridge-v2" as const;
export const tokenTicketSchemaVersion = "token-ticket-v2" as const;

export const redevPluginContractVersions = {
  "plugin_ui_protocol_version": "plugin-ui-v2",
  "plugin_host_protocol_version": "plugin-host-v2",
  "rust_ipc_version": "rust-ipc-v1",
  "wasm_abi_version": "redevplugin-wasm-worker-v1",
  "manifest_schema_version": "manifest-v2",
  "package_signature_schema_version": "package-signature-v1",
  "release_metadata_schema_version": "release-metadata-v2",
  "source_policy_schema_version": "source-policy-v1",
  "source_revocations_schema_version": "source-revocations-v1",
  "token_ticket_schema_version": "token-ticket-v2",
  "bridge_schema_version": "bridge-v2",
  "opaque_surface_document_schema_version": "opaque-surface-document-v1",
  "opaque_surface_transport_schema_version": "opaque-surface-transport-v1",
  "target_classifier_version": "target-classifier-v1",
  "network_grant_schema_version": "network-grant-v1",
  "plugin_platform_openapi_version": "plugin-platform-v2",
  "compatibility_manifest_version": "redevplugin.compatibility.v2",
  "compatibility_schema_version": "compatibility-manifest-v2",
  "release_manifest_schema_version": "release-manifest-v2",
  "worker_invocation_schema_version": "worker-invocation-v1",
  "error_codes_schema_version": "error-codes-v1",
  "contract_registry_version": "contract-registry-v1",
} as const;

export type ReDevPluginContractArtifact = {
  readonly id: string;
  readonly path: string;
  readonly version: string;
  readonly sha256: string;
};

export const redevPluginContractArtifacts = [
  {
    id: "plugin-platform-openapi",
    path: "spec/openapi/plugin-platform-v2.yaml",
    version: "plugin-platform-v2",
    sha256: "5d6006831c3e55cd9232ad8f9decdc932059193538f9f0ff2b3934d81a6b9aaa",
  },
  {
    id: "manifest-schema",
    path: "spec/plugin/manifest-v2.schema.json",
    version: "manifest-v2",
    sha256: "ba2f782e0e47694484d4112da00d92689187e3bbd1e2f08aca2d9d680e554d51",
  },
  {
    id: "package-signature-schema",
    path: "spec/plugin/package-signature-v1.schema.json",
    version: "package-signature-v1",
    sha256: "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
  },
  {
    id: "release-metadata-schema",
    path: "spec/plugin/release-metadata-v2.schema.json",
    version: "release-metadata-v2",
    sha256: "6f985f9b0f009151b41e878c68f217058f7dd892f7f6471b2e5d24f54d858567",
  },
  {
    id: "source-policy-schema",
    path: "spec/plugin/source-policy-v1.schema.json",
    version: "source-policy-v1",
    sha256: "b5f3094402bdbfdda1671b46e5f64a69ad7dc2ba9501030439fafa87acd2923e",
  },
  {
    id: "source-revocations-schema",
    path: "spec/plugin/source-revocations-v1.schema.json",
    version: "source-revocations-v1",
    sha256: "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
  },
  {
    id: "token-ticket-schema",
    path: "spec/plugin/token-ticket-v2.schema.json",
    version: "token-ticket-v2",
    sha256: "f2fa0d5948318a7a61a3e52d1487b308891d65578259d5958b26c59adef0f351",
  },
  {
    id: "iframe-bridge-schema",
    path: "spec/plugin/bridge-v2.schema.json",
    version: "bridge-v2",
    sha256: "6a6f33381503d67fd7c3098e5e73b8d01ba80b0145190bdd034f85fd43528f23",
  },
  {
    id: "opaque-surface-document-schema",
    path: "spec/plugin/opaque-surface-document-v1.schema.json",
    version: "opaque-surface-document-v1",
    sha256: "78ca8f1fb161dd5cdd54d192eb3e147d6f0e6a8b9de01652ecd4b255600ea9b7",
  },
  {
    id: "opaque-surface-transport-schema",
    path: "spec/plugin/opaque-surface-transport-v1.schema.json",
    version: "opaque-surface-transport-v1",
    sha256: "36cd3378393fc8b59da0e3beb345d56db9a52548604177f0adc36e40d4d2b29b",
  },
  {
    id: "compatibility-manifest-schema",
    path: "spec/plugin/compatibility-manifest-v2.schema.json",
    version: "compatibility-manifest-v2",
    sha256: "924c117966bfc322b643e2987d1387f15ebd5222f328171c66eb56d24d281e21",
  },
  {
    id: "release-manifest-schema",
    path: "spec/plugin/release-manifest-v2.schema.json",
    version: "release-manifest-v2",
    sha256: "4406be65353d6d6e059cc0bd279c6ffc53c4250dd5407e7435b30b2fd6a0f582",
  },
  {
    id: "worker-invocation-schema",
    path: "spec/plugin/worker-invocation-v1.schema.json",
    version: "worker-invocation-v1",
    sha256: "cbbef78febae6d13d914bf382d22f2d9785d0bac158eb92d18a2815d5c70dbe6",
  },
  {
    id: "error-codes-schema",
    path: "spec/plugin/error-codes-v1.schema.json",
    version: "error-codes-v1",
    sha256: "89c95342f689b0ad486631f85ce73d4ffc86babe4e827ac6c2337e50bddc536e",
  },
  {
    id: "rust-ipc-schema",
    path: "spec/plugin/ipc-v1.schema.json",
    version: "rust-ipc-v1",
    sha256: "4e3a9556392b06b805f36fe80c5690408d702a72d71ac6f6e3edcb31f2fd0e91",
  },
  {
    id: "wasm-worker-schema",
    path: "spec/plugin/wasm-worker-v1.schema.json",
    version: "redevplugin-wasm-worker-v1",
    sha256: "ff0a37ea972db7d8be89b529e03d890af00aab3f2d9461c2db3a3d58c664b775",
  },
  {
    id: "network-grant-schema",
    path: "spec/plugin/network-grant-v1.schema.json",
    version: "network-grant-v1",
    sha256: "e3ba8e7aa42267596b5570c1de60994a0912b125ea78427776db8092c2b3ea7b",
  },
  {
    id: "target-classifier-fixture",
    path: "spec/plugin/target-classifier-v1.json",
    version: "target-classifier-v1",
    sha256: "7e9367d624c22d575ae5c118063c1cb0f0de6b5b0081eabcfc51c0357e4d14d7",
  },
  {
    id: "contract-registry",
    path: "spec/plugin/contract-registry-v1.json",
    version: "contract-registry-v1",
    sha256: "753d9e86abc10957ee2a80ae87b5ebf1b83af70370afc1c4e838efa6854eb8f9",
  },
] as const satisfies readonly ReDevPluginContractArtifact[];
