// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

export const pluginUIProtocolVersion = "plugin-ui-v2" as const;
export const pluginHostProtocolVersion = "plugin-host-v2" as const;
export const bridgeSchemaVersion = "bridge-v2" as const;
export const tokenTicketSchemaVersion = "token-ticket-v2" as const;

export const redevPluginContractVersions = {
  "plugin_ui_protocol_version": "plugin-ui-v2",
  "plugin_host_protocol_version": "plugin-host-v2",
  "rust_ipc_version": "rust-ipc-v1",
  "wasm_abi_version": "redevplugin-wasm-worker-v1",
  "manifest_schema_version": "manifest-v2",
  "package_signature_schema_version": "package-signature-v1",
  "release_metadata_schema_version": "release-metadata-v2",
  "source_policy_schema_version": "source-policy-v1",
  "source_revocations_schema_version": "source-revocations-v1",
  "token_ticket_schema_version": "token-ticket-v2",
  "bridge_schema_version": "bridge-v2",
  "opaque_surface_document_schema_version": "opaque-surface-document-v1",
  "opaque_surface_transport_schema_version": "opaque-surface-transport-v1",
  "target_classifier_version": "target-classifier-v1",
  "network_grant_schema_version": "network-grant-v1",
  "plugin_platform_openapi_version": "plugin-platform-v2",
  "compatibility_manifest_version": "redevplugin.compatibility.v2",
  "compatibility_schema_version": "compatibility-manifest-v2",
  "release_manifest_schema_version": "release-manifest-v2",
  "worker_invocation_schema_version": "worker-invocation-v1",
  "host_capability_contract_schema_version": "host-capability-contract-v1",
  "host_capability_pin_schema_version": "host-capability-pin-v1",
  "host_capability_manifest_schema_version": "host-capability-manifest-v1",
  "host_capability_compatibility_schema_version": "host-capability-compatibility-v1",
  "host_capability_signature_schema_version": "host-capability-signature-v1",
  "host_capability_notices_schema_version": "host-capability-notices-v1",
  "error_codes_schema_version": "error-codes-v1",
  "contract_registry_version": "contract-registry-v1",
} as const;

export type ReDevPluginContractArtifact = {
  readonly id: string;
  readonly path: string;
  readonly version: string;
  readonly sha256: string;
};

export const redevPluginContractArtifacts = [
  {
    id: "plugin-platform-openapi",
    path: "spec/openapi/plugin-platform-v2.yaml",
    version: "plugin-platform-v2",
    sha256: "b7922ebd37be680060f067b66a439f3d1f9a7f22d730512763e3f7d347dcaf9a",
  },
  {
    id: "manifest-schema",
    path: "spec/plugin/manifest-v2.schema.json",
    version: "manifest-v2",
    sha256: "f80279943bde0e304138ee0fdae2e7b9f2b0334412cf159d268cc8badc196759",
  },
  {
    id: "package-signature-schema",
    path: "spec/plugin/package-signature-v1.schema.json",
    version: "package-signature-v1",
    sha256: "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
  },
  {
    id: "release-metadata-schema",
    path: "spec/plugin/release-metadata-v2.schema.json",
    version: "release-metadata-v2",
    sha256: "5f24cf61bea352715f24595c385745476e677affdaf8f60fd15e534424df60b6",
  },
  {
    id: "source-policy-schema",
    path: "spec/plugin/source-policy-v1.schema.json",
    version: "source-policy-v1",
    sha256: "fb6a9c27e726378a28a9ff48ee47c40ede99fa95a524a308e2c762bebc4b9fe2",
  },
  {
    id: "source-revocations-schema",
    path: "spec/plugin/source-revocations-v1.schema.json",
    version: "source-revocations-v1",
    sha256: "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
  },
  {
    id: "token-ticket-schema",
    path: "spec/plugin/token-ticket-v2.schema.json",
    version: "token-ticket-v2",
    sha256: "f0342614f28b81045ac47d76d71753c8ee177f8143c14a711a0b1f5632e7835e",
  },
  {
    id: "iframe-bridge-schema",
    path: "spec/plugin/bridge-v2.schema.json",
    version: "bridge-v2",
    sha256: "23d968113aaf93dab75df6acd96a350df07c0428fd2a00c66c015a0d875592d1",
  },
  {
    id: "opaque-surface-document-schema",
    path: "spec/plugin/opaque-surface-document-v1.schema.json",
    version: "opaque-surface-document-v1",
    sha256: "78ca8f1fb161dd5cdd54d192eb3e147d6f0e6a8b9de01652ecd4b255600ea9b7",
  },
  {
    id: "opaque-surface-transport-schema",
    path: "spec/plugin/opaque-surface-transport-v1.schema.json",
    version: "opaque-surface-transport-v1",
    sha256: "36cd3378393fc8b59da0e3beb345d56db9a52548604177f0adc36e40d4d2b29b",
  },
  {
    id: "compatibility-manifest-schema",
    path: "spec/plugin/compatibility-manifest-v2.schema.json",
    version: "compatibility-manifest-v2",
    sha256: "7e0789cc80f4674277c6d12f4e097198543081b198b7a1a94eefb3cd404c6eb0",
  },
  {
    id: "release-manifest-schema",
    path: "spec/plugin/release-manifest-v2.schema.json",
    version: "release-manifest-v2",
    sha256: "4406be65353d6d6e059cc0bd279c6ffc53c4250dd5407e7435b30b2fd6a0f582",
  },
  {
    id: "worker-invocation-schema",
    path: "spec/plugin/worker-invocation-v1.schema.json",
    version: "worker-invocation-v1",
    sha256: "9199dd0731aaf592e34c1574cd81c094412a3e6cd9b633853d3e60e89438bcb5",
  },
  {
    id: "host-capability-contract-schema",
    path: "spec/plugin/host-capability-contract-v1.schema.json",
    version: "host-capability-contract-v1",
    sha256: "a2318b01211aa6dbd8ca983f7ebca311619527aa4828a0ea0d201ebac7427292",
  },
  {
    id: "host-capability-pin-schema",
    path: "spec/plugin/host-capability-pin-v1.schema.json",
    version: "host-capability-pin-v1",
    sha256: "20526a5934f0d85a3db7882492487266f09de5bcd176e2c7936f05d0b7fe0338",
  },
  {
    id: "host-capability-manifest-schema",
    path: "spec/plugin/host-capability-manifest-v1.schema.json",
    version: "host-capability-manifest-v1",
    sha256: "5f13a8e5f918378b9cba9fdc133a9a75ba3a8311c30cb6a02ca0aba09035110e",
  },
  {
    id: "host-capability-compatibility-schema",
    path: "spec/plugin/host-capability-compatibility-v1.schema.json",
    version: "host-capability-compatibility-v1",
    sha256: "361ebbf7009aeb66c763ecde46427b17b6cf7d2307c01886c5987a1f4f1762de",
  },
  {
    id: "host-capability-signature-schema",
    path: "spec/plugin/host-capability-signature-v1.schema.json",
    version: "host-capability-signature-v1",
    sha256: "88cbc1d63afb7e289ca4f8b7c76f702b8d20156f7722c1b71f3ab9138a240a5e",
  },
  {
    id: "host-capability-notices-schema",
    path: "spec/plugin/host-capability-notices-v1.schema.json",
    version: "host-capability-notices-v1",
    sha256: "6affd5d0ae90239f6fd08cbeddae4eef393efa2838c9e4935874ba3dc0e05948",
  },
  {
    id: "error-codes-schema",
    path: "spec/plugin/error-codes-v1.schema.json",
    version: "error-codes-v1",
    sha256: "254eb4c6d25bae3976c30fe51bdd49456e906e1a3f3bc76df092afd30bd4c948",
  },
  {
    id: "rust-ipc-schema",
    path: "spec/plugin/ipc-v1.schema.json",
    version: "rust-ipc-v1",
    sha256: "78f1310a0b48db733301c3f163ada041a3c9daf2d09369860d758296cbe12e39",
  },
  {
    id: "wasm-worker-schema",
    path: "spec/plugin/wasm-worker-v1.schema.json",
    version: "redevplugin-wasm-worker-v1",
    sha256: "ff0a37ea972db7d8be89b529e03d890af00aab3f2d9461c2db3a3d58c664b775",
  },
  {
    id: "network-grant-schema",
    path: "spec/plugin/network-grant-v1.schema.json",
    version: "network-grant-v1",
    sha256: "e3ba8e7aa42267596b5570c1de60994a0912b125ea78427776db8092c2b3ea7b",
  },
  {
    id: "target-classifier-fixture",
    path: "spec/plugin/target-classifier-v1.json",
    version: "target-classifier-v1",
    sha256: "7e9367d624c22d575ae5c118063c1cb0f0de6b5b0081eabcfc51c0357e4d14d7",
  },
  {
    id: "contract-registry",
    path: "spec/plugin/contract-registry-v1.json",
    version: "contract-registry-v1",
    sha256: "42dd916922a6183b49d4abc765da2e2d086771a6e6ac1828f8e1dbebb262bba0",
  },
] as const satisfies readonly ReDevPluginContractArtifact[];
