// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

export const pluginUIProtocolVersion = "plugin-ui-v4" as const;
export const pluginHostProtocolVersion = "plugin-host-v2" as const;
export const bridgeSchemaVersion = "bridge-v4" as const;
export const tokenTicketSchemaVersion = "token-ticket-v2" as const;

export const redevPluginContractVersions = {
  "plugin_ui_protocol_version": "plugin-ui-v4",
  "plugin_host_protocol_version": "plugin-host-v2",
  "rust_ipc_version": "rust-ipc-v2",
  "wasm_abi_version": "redevplugin-wasm-worker-v2",
  "manifest_schema_version": "manifest-v4",
  "package_signature_schema_version": "package-signature-v1",
  "release_metadata_schema_version": "release-metadata-v4",
  "source_policy_schema_version": "source-policy-v1",
  "source_revocations_schema_version": "source-revocations-v1",
  "token_ticket_schema_version": "token-ticket-v2",
  "bridge_schema_version": "bridge-v4",
  "opaque_surface_document_schema_version": "opaque-surface-document-v2",
  "opaque_surface_transport_schema_version": "opaque-surface-transport-v3",
  "target_classifier_version": "target-classifier-v1",
  "network_grant_schema_version": "network-grant-v1",
  "plugin_platform_openapi_version": "plugin-platform-v4",
  "compatibility_manifest_version": "redevplugin.compatibility.v4",
  "compatibility_schema_version": "compatibility-manifest-v4",
  "release_manifest_schema_version": "release-manifest-v3",
  "worker_invocation_schema_version": "worker-invocation-v2",
  "host_capability_contract_schema_version": "host-capability-contract-v1",
  "host_capability_pin_schema_version": "host-capability-pin-v1",
  "host_capability_manifest_schema_version": "host-capability-manifest-v1",
  "host_capability_compatibility_schema_version": "host-capability-compatibility-v1",
  "host_capability_signature_schema_version": "host-capability-signature-v1",
  "host_capability_notices_schema_version": "host-capability-notices-v1",
  "error_codes_schema_version": "error-codes-v2",
  "contract_registry_version": "contract-registry-v1",
} as const;

export type ReDevPluginContractArtifact = {
  readonly id: string;
  readonly path: string;
  readonly version: string;
  readonly sha256: string;
};

export const redevPluginContractArtifacts = [
  {
    id: "plugin-platform-openapi",
    path: "spec/openapi/plugin-platform-v4.yaml",
    version: "plugin-platform-v4",
    sha256: "a7373077e0268c7b3b861fef24734763eeb339ebd92c7d6d13ae514759b0f3b5",
  },
  {
    id: "manifest-schema",
    path: "spec/plugin/manifest-v4.schema.json",
    version: "manifest-v4",
    sha256: "5bbe47381fbdab1d5622389df5db922ff24db32891305e89a9b70e4dfae25596",
  },
  {
    id: "package-signature-schema",
    path: "spec/plugin/package-signature-v1.schema.json",
    version: "package-signature-v1",
    sha256: "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
  },
  {
    id: "release-metadata-schema",
    path: "spec/plugin/release-metadata-v4.schema.json",
    version: "release-metadata-v4",
    sha256: "c4d0a400e668175f2a9909b7ccacf379f2412053e8cc8458d5f31d45ee28ffc7",
  },
  {
    id: "source-policy-schema",
    path: "spec/plugin/source-policy-v1.schema.json",
    version: "source-policy-v1",
    sha256: "fb6a9c27e726378a28a9ff48ee47c40ede99fa95a524a308e2c762bebc4b9fe2",
  },
  {
    id: "source-revocations-schema",
    path: "spec/plugin/source-revocations-v1.schema.json",
    version: "source-revocations-v1",
    sha256: "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
  },
  {
    id: "token-ticket-schema",
    path: "spec/plugin/token-ticket-v2.schema.json",
    version: "token-ticket-v2",
    sha256: "f0342614f28b81045ac47d76d71753c8ee177f8143c14a711a0b1f5632e7835e",
  },
  {
    id: "iframe-bridge-schema",
    path: "spec/plugin/bridge-v4.schema.json",
    version: "bridge-v4",
    sha256: "1ccc10db182ee8e5b4351e4fc3138382cb07ff14f953e62b280538dbe656fe81",
  },
  {
    id: "opaque-surface-document-schema",
    path: "spec/plugin/opaque-surface-document-v2.schema.json",
    version: "opaque-surface-document-v2",
    sha256: "abb0836bfb53089abd6522269265cc9f9e9bbc5b3cfc6d956404f6208b3e7238",
  },
  {
    id: "opaque-surface-transport-schema",
    path: "spec/plugin/opaque-surface-transport-v3.schema.json",
    version: "opaque-surface-transport-v3",
    sha256: "ce718ceb09d8649b642cb59647fa529acfc4d53d57f31788a2bcba08aa9319c6",
  },
  {
    id: "compatibility-manifest-schema",
    path: "spec/plugin/compatibility-manifest-v4.schema.json",
    version: "compatibility-manifest-v4",
    sha256: "d0804bf5a6069c8727ae0fc00c822fd1a36997a36231da01d8217a716f35d670",
  },
  {
    id: "release-manifest-schema",
    path: "spec/plugin/release-manifest-v3.schema.json",
    version: "release-manifest-v3",
    sha256: "8c3fda908cd71169b2daf7d2a4e0b5b0c26a32e125a567304d872633fc05309b",
  },
  {
    id: "worker-invocation-schema",
    path: "spec/plugin/worker-invocation-v2.schema.json",
    version: "worker-invocation-v2",
    sha256: "9a8843d19db04334525fd308a6b54fe26b12e3b4a0da46b417687e76629bd7d0",
  },
  {
    id: "host-capability-contract-schema",
    path: "spec/plugin/host-capability-contract-v1.schema.json",
    version: "host-capability-contract-v1",
    sha256: "a2318b01211aa6dbd8ca983f7ebca311619527aa4828a0ea0d201ebac7427292",
  },
  {
    id: "host-capability-pin-schema",
    path: "spec/plugin/host-capability-pin-v1.schema.json",
    version: "host-capability-pin-v1",
    sha256: "20526a5934f0d85a3db7882492487266f09de5bcd176e2c7936f05d0b7fe0338",
  },
  {
    id: "host-capability-manifest-schema",
    path: "spec/plugin/host-capability-manifest-v1.schema.json",
    version: "host-capability-manifest-v1",
    sha256: "5f13a8e5f918378b9cba9fdc133a9a75ba3a8311c30cb6a02ca0aba09035110e",
  },
  {
    id: "host-capability-compatibility-schema",
    path: "spec/plugin/host-capability-compatibility-v1.schema.json",
    version: "host-capability-compatibility-v1",
    sha256: "361ebbf7009aeb66c763ecde46427b17b6cf7d2307c01886c5987a1f4f1762de",
  },
  {
    id: "host-capability-signature-schema",
    path: "spec/plugin/host-capability-signature-v1.schema.json",
    version: "host-capability-signature-v1",
    sha256: "88cbc1d63afb7e289ca4f8b7c76f702b8d20156f7722c1b71f3ab9138a240a5e",
  },
  {
    id: "host-capability-notices-schema",
    path: "spec/plugin/host-capability-notices-v1.schema.json",
    version: "host-capability-notices-v1",
    sha256: "6affd5d0ae90239f6fd08cbeddae4eef393efa2838c9e4935874ba3dc0e05948",
  },
  {
    id: "error-codes-schema",
    path: "spec/plugin/error-codes-v2.schema.json",
    version: "error-codes-v2",
    sha256: "d7eae5515043df64558763d391cf6b8e7970def6661d7f4eb5b648bd3bc7acd7",
  },
  {
    id: "rust-ipc-schema",
    path: "spec/plugin/ipc-v2.schema.json",
    version: "rust-ipc-v2",
    sha256: "8c9dc1fe60da2399647efaad58b871860c278810ba4a6c357d904e2414a29aed",
  },
  {
    id: "wasm-worker-schema",
    path: "spec/plugin/wasm-worker-v2.schema.json",
    version: "redevplugin-wasm-worker-v2",
    sha256: "d2ef05ffed74706cf0683a57665068c5bdf2b191a6c20cb876ec1049798afeaf",
  },
  {
    id: "network-grant-schema",
    path: "spec/plugin/network-grant-v1.schema.json",
    version: "network-grant-v1",
    sha256: "e3ba8e7aa42267596b5570c1de60994a0912b125ea78427776db8092c2b3ea7b",
  },
  {
    id: "target-classifier-fixture",
    path: "spec/plugin/target-classifier-v1.json",
    version: "target-classifier-v1",
    sha256: "7e9367d624c22d575ae5c118063c1cb0f0de6b5b0081eabcfc51c0357e4d14d7",
  },
  {
    id: "contract-registry",
    path: "spec/plugin/contract-registry-v1.json",
    version: "contract-registry-v1",
    sha256: "5800d692798ccac8407f3e444dc49cdf1fcde6abc74a3c3f72198ab1a4633c7a",
  },
] as const satisfies readonly ReDevPluginContractArtifact[];
