// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

export const opaqueSurfaceAllowedTags = [
  "main",
  "section",
  "header",
  "footer",
  "nav",
  "aside",
  "article",
  "div",
  "span",
  "p",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "button",
  "input",
  "textarea",
  "select",
  "option",
  "label",
  "fieldset",
  "legend",
  "form",
  "ul",
  "ol",
  "li",
  "dl",
  "dt",
  "dd",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "tr",
  "th",
  "td",
  "caption",
  "details",
  "summary",
  "pre",
  "code",
  "kbd",
  "samp",
  "strong",
  "em",
  "small",
  "mark",
  "time",
  "progress",
  "meter",
  "img",
  "picture",
  "source",
  "audio",
  "video",
  "track",
  "canvas"
] as const;
export type OpaqueSurfaceAllowedTag = (typeof opaqueSurfaceAllowedTags)[number];

export const opaqueSurfaceGlobalAttributes = [
  "id",
  "class",
  "role",
  "title",
  "hidden",
  "tabindex",
  "autofocus",
  "lang",
  "dir",
  "data-redevplugin-action",
  "data-redevplugin-escape-action",
  "data-redevplugin-asset-binding",
  "data-redevplugin-asset-attr"
] as const;

export const opaqueSurfaceTagAttributes = {
  "button": [
    "type",
    "name",
    "value",
    "disabled",
    "aria-pressed",
    "aria-expanded"
  ],
  "input": [
    "type",
    "name",
    "value",
    "checked",
    "disabled",
    "readonly",
    "required",
    "placeholder",
    "min",
    "max",
    "step",
    "autocomplete"
  ],
  "textarea": [
    "name",
    "value",
    "disabled",
    "readonly",
    "required",
    "placeholder",
    "rows",
    "cols",
    "maxlength"
  ],
  "select": [
    "name",
    "disabled",
    "required",
    "multiple",
    "size"
  ],
  "option": [
    "value",
    "selected",
    "disabled",
    "label"
  ],
  "label": [
    "for"
  ],
  "form": [
    "name",
    "autocomplete"
  ],
  "th": [
    "scope",
    "colspan",
    "rowspan"
  ],
  "td": [
    "colspan",
    "rowspan"
  ],
  "progress": [
    "value",
    "max"
  ],
  "meter": [
    "value",
    "min",
    "max",
    "low",
    "high",
    "optimum"
  ],
  "img": [
    "alt",
    "width",
    "height",
    "loading",
    "decoding"
  ],
  "audio": [
    "controls",
    "autoplay",
    "muted",
    "loop",
    "preload"
  ],
  "video": [
    "controls",
    "autoplay",
    "muted",
    "loop",
    "preload",
    "width",
    "height",
    "playsinline"
  ],
  "source": [
    "type",
    "media"
  ],
  "track": [
    "kind",
    "srclang",
    "label",
    "default"
  ],
  "time": [
    "datetime"
  ],
  "canvas": [
    "width",
    "height",
    "data-redevplugin-canvas"
  ]
} as const;

export const opaqueSurfaceSafeInputTypes = [
  "text",
  "search",
  "number",
  "checkbox",
  "radio",
  "button",
  "submit",
  "reset"
] as const;

export const opaqueSurfaceRenderLimits = {
  "max_message_bytes": 262144,
  "max_in_flight_requests": 256,
  "max_renders_per_second": 60,
  "max_render_depth": 32,
  "max_render_nodes": 4096,
  "max_attributes_per_element": 64,
  "max_text_length": 65536,
  "max_attribute_value_length": 4096,
  "max_form_fields": 128,
  "max_canvas_count": 4,
  "max_canvas_dimension": 4096,
  "max_canvas_total_pixels": 16777216,
  "max_canvas_pointer_events_per_second": 120,
  "max_image_count": 32,
  "max_image_dimension": 4096,
  "max_image_total_pixels": 33554432,
  "worker_heartbeat_interval_ms": 10000,
  "worker_heartbeat_timeout_ms": 5000
} as const;
