package httpadapter

import (
	"bytes"
	"crypto/subtle"
	"errors"
	"io"
	"net/http"
	"os"
	"testing"

	"github.com/floegence/redevplugin/internal/performanceevidence"
	"github.com/floegence/redevplugin/pkg/sessionctx"
	"github.com/floegence/redevplugin/pkg/websecurity"
)

const (
	routeAuthorizationOrigin = "https://host.performance.invalid"
	routeAuthorizationCSRF   = "route-authorization-csrf-v1"
	routeAuthorizationBearer = "Bearer route-authorization-v1"
)

func TestRouteAuthorizationPerformanceEvidence(t *testing.T) {
	output := os.Getenv("REDEVPLUGIN_ROUTE_AUTHORIZATION_PROFILE")
	if output == "" {
		t.Skip("route authorization performance profile is generated by the performance runner")
	}
	request, err := http.NewRequest(http.MethodPost, routeAuthorizationOrigin+"/_redevplugin/api/plugins/enable", http.NoBody)
	if err != nil {
		t.Fatal(err)
	}
	request.Header.Set("Authorization", routeAuthorizationBearer)
	request.Header.Set("Origin", routeAuthorizationOrigin)
	request.Header.Set("X-ReDevPlugin-CSRF", routeAuthorizationCSRF)
	request.Header.Set("Content-Type", "application/json")
	handler := mustNewHandler(t, newHTTPTestHost(t), routeAuthorizationPerformanceGuard{})
	queryBody := []byte("{}")
	profile, err := performanceevidence.MeasureRouteAuthorization(
		"v0.6.0",
		os.Getenv("REDEVPLUGIN_ROUTE_AUTHORIZATION_COMMIT"),
		func() error {
			isolated := *request
			isolated.Body = io.NopCloser(bytes.NewReader(queryBody))
			isolated.ContentLength = int64(len(queryBody))
			writer := routeAuthorizationResponseWriter{header: make(http.Header)}
			handler.ServeHTTP(&writer, &isolated)
			if writer.status != http.StatusBadRequest {
				return errors.New("authenticated route authorization request failed")
			}
			return nil
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if err := performanceevidence.ValidateRouteAuthorizationProfile(profile); err != nil {
		t.Fatal(err)
	}
	if err := performanceevidence.WriteRouteAuthorizationProfile(output, profile); err != nil {
		t.Fatal(err)
	}
}

type routeAuthorizationResponseWriter struct {
	header http.Header
	status int
}

func (w *routeAuthorizationResponseWriter) Header() http.Header { return w.header }
func (w *routeAuthorizationResponseWriter) Write(body []byte) (int, error) {
	if w.status == 0 {
		w.status = http.StatusOK
	}
	return len(body), nil
}
func (w *routeAuthorizationResponseWriter) WriteHeader(status int) { w.status = status }

type routeAuthorizationPerformanceGuard struct{}

func (routeAuthorizationPerformanceGuard) Authenticate(request *http.Request) (sessionctx.Context, error) {
	if !routeAuthorizationHeaderMatches(request.Header, "Authorization", routeAuthorizationBearer) {
		return sessionctx.Context{}, errors.New("authorization header mismatch")
	}
	return sessionctx.Context{
		OwnerSessionHash:     "route_authorization_session",
		OwnerUserHash:        "route_authorization_user",
		OwnerEnvHash:         "route_authorization_environment",
		SessionChannelIDHash: "route_authorization_channel",
	}, nil
}

func (routeAuthorizationPerformanceGuard) ValidateOrigin(request *http.Request, _ sessionctx.Context, policy websecurity.OriginPolicy) error {
	if policy != websecurity.OriginPolicyTrustedHost || !routeAuthorizationHeaderMatches(request.Header, "Origin", routeAuthorizationOrigin) {
		return websecurity.ErrOriginDenied
	}
	return nil
}

func (routeAuthorizationPerformanceGuard) ValidateCSRF(request *http.Request, _ sessionctx.Context, policy websecurity.CSRFPolicy) error {
	if policy != websecurity.CSRFPolicyRequired || !routeAuthorizationHeaderMatches(request.Header, "X-ReDevPlugin-CSRF", routeAuthorizationCSRF) {
		return websecurity.ErrCSRFInvalid
	}
	return nil
}

func (routeAuthorizationPerformanceGuard) AuthorizeRoute(_ *http.Request, _ sessionctx.Context, action websecurity.RouteAction, effect websecurity.RouteEffect) error {
	if action != websecurity.RouteActionEnablePlugin {
		return websecurity.ErrRouteActionInvalid
	}
	if effect != websecurity.RouteEffectMutation {
		return websecurity.ErrRouteEffectInvalid
	}
	return nil
}

func routeAuthorizationHeaderMatches(header http.Header, name, expected string) bool {
	values := header.Values(name)
	if len(values) != 1 || len(values[0]) != len(expected) {
		return false
	}
	equal := 1
	for index := range expected {
		equal &= subtle.ConstantTimeByteEq(values[0][index], expected[index])
	}
	return equal == 1
}
