// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

package pluginpkg

const (
	opaqueSurfaceMaxMessageBytes         = 262144
	opaqueSurfaceMaxInFlightRequests     = 256
	opaqueSurfaceMaxRendersPerSecond     = 30
	opaqueSurfaceMaxRenderDepth          = 32
	opaqueSurfaceMaxRenderNodes          = 4096
	opaqueSurfaceMaxAttributesPerElement = 64
	opaqueSurfaceMaxTextLength           = 65536
	opaqueSurfaceMaxAttributeValueLength = 4096
	opaqueSurfaceMaxFormFields           = 128
)

var opaqueSurfaceAllowedTags = map[string]struct{}{
	"main":     {},
	"section":  {},
	"header":   {},
	"footer":   {},
	"nav":      {},
	"aside":    {},
	"article":  {},
	"div":      {},
	"span":     {},
	"p":        {},
	"h1":       {},
	"h2":       {},
	"h3":       {},
	"h4":       {},
	"h5":       {},
	"h6":       {},
	"button":   {},
	"input":    {},
	"textarea": {},
	"select":   {},
	"option":   {},
	"label":    {},
	"fieldset": {},
	"legend":   {},
	"form":     {},
	"ul":       {},
	"ol":       {},
	"li":       {},
	"dl":       {},
	"dt":       {},
	"dd":       {},
	"table":    {},
	"thead":    {},
	"tbody":    {},
	"tfoot":    {},
	"tr":       {},
	"th":       {},
	"td":       {},
	"caption":  {},
	"details":  {},
	"summary":  {},
	"pre":      {},
	"code":     {},
	"kbd":      {},
	"samp":     {},
	"strong":   {},
	"em":       {},
	"small":    {},
	"mark":     {},
	"time":     {},
	"progress": {},
	"meter":    {},
	"img":      {},
	"picture":  {},
	"source":   {},
	"audio":    {},
	"video":    {},
	"track":    {},
}

var opaqueSurfaceGlobalAttributes = map[string]struct{}{
	"id":                             {},
	"class":                          {},
	"role":                           {},
	"title":                          {},
	"hidden":                         {},
	"tabindex":                       {},
	"lang":                           {},
	"dir":                            {},
	"data-redevplugin-action":        {},
	"data-redevplugin-asset-binding": {},
	"data-redevplugin-asset-attr":    {},
}

var opaqueSurfaceTagAttributes = map[string]map[string]struct{}{
	"button": {
		"type":          {},
		"name":          {},
		"value":         {},
		"disabled":      {},
		"aria-pressed":  {},
		"aria-expanded": {},
	},
	"input": {
		"type":         {},
		"name":         {},
		"value":        {},
		"checked":      {},
		"disabled":     {},
		"readonly":     {},
		"required":     {},
		"placeholder":  {},
		"min":          {},
		"max":          {},
		"step":         {},
		"autocomplete": {},
	},
	"textarea": {
		"name":        {},
		"disabled":    {},
		"readonly":    {},
		"required":    {},
		"placeholder": {},
		"rows":        {},
		"cols":        {},
		"maxlength":   {},
	},
	"select": {
		"name":     {},
		"disabled": {},
		"required": {},
		"multiple": {},
		"size":     {},
	},
	"option": {
		"value":    {},
		"selected": {},
		"disabled": {},
		"label":    {},
	},
	"label": {
		"for": {},
	},
	"form": {
		"name":         {},
		"autocomplete": {},
	},
	"th": {
		"scope":   {},
		"colspan": {},
		"rowspan": {},
	},
	"td": {
		"colspan": {},
		"rowspan": {},
	},
	"progress": {
		"value": {},
		"max":   {},
	},
	"meter": {
		"value":   {},
		"min":     {},
		"max":     {},
		"low":     {},
		"high":    {},
		"optimum": {},
	},
	"img": {
		"alt":      {},
		"width":    {},
		"height":   {},
		"loading":  {},
		"decoding": {},
	},
	"audio": {
		"controls": {},
		"autoplay": {},
		"muted":    {},
		"loop":     {},
		"preload":  {},
	},
	"video": {
		"controls":    {},
		"autoplay":    {},
		"muted":       {},
		"loop":        {},
		"preload":     {},
		"width":       {},
		"height":      {},
		"playsinline": {},
	},
	"source": {
		"type":  {},
		"media": {},
	},
	"track": {
		"kind":    {},
		"srclang": {},
		"label":   {},
		"default": {},
	},
	"time": {
		"datetime": {},
	},
}

var opaqueSurfaceSafeInputTypes = map[string]struct{}{
	"text":     {},
	"search":   {},
	"number":   {},
	"checkbox": {},
	"radio":    {},
	"button":   {},
	"submit":   {},
	"reset":    {},
}
