#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");

const result = await build({
  entryPoints: [resolve(root, "internal/scaffoldtemplate/plugin-worker.ts")],
  alias: {
    "@floegence/redevplugin-ui/plugin": resolve(root, "packages/redevplugin-ui/src/plugin.ts"),
  },
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  sourcemap: false,
  write: false,
  logLevel: "silent",
});
if (result.outputFiles.length !== 1) throw new Error("expected one bundled scaffold UI worker");
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/plugin-worker.js",
  Buffer.from(`// Code generated by scripts/build_scaffold_assets.mjs; DO NOT EDIT.\n${result.outputFiles[0].text}`),
);
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/plugin-worker.ts",
  await readFile(resolve(root, "internal/scaffoldtemplate/plugin-worker.ts")),
);
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/worker-lib.rs",
  await readFile(resolve(root, "internal/scaffoldworker/src/lib.rs")),
);

const cargo = await cargoPath();
const cargoBuild = spawnSync(cargo, [
  "build",
  "--release",
  "--target",
  "wasm32-unknown-unknown",
  "-p",
  "redevplugin-scaffold-worker",
], {
  cwd: root,
  env: process.env,
  encoding: "utf8",
});
if (cargoBuild.status !== 0) {
  process.stderr.write(cargoBuild.stdout || "");
  process.stderr.write(cargoBuild.stderr || "");
  throw new Error("failed to build the scaffold WASM worker");
}
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/backend.wasm",
  await readFile(resolve(root, "target/wasm32-unknown-unknown/release/redevplugin_scaffold_worker.wasm")),
);

async function verifyOrWrite(relativePath, content) {
  const outputPath = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(outputPath).catch(() => Buffer.alloc(0));
    if (!current.equals(content)) {
      throw new Error(`${relativePath} is stale; run npm run scaffold:generate`);
    }
    return;
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}

async function cargoPath() {
  const bundled = resolve(homedir(), ".cargo/bin/cargo");
  try {
    await access(bundled);
    return bundled;
  } catch {
    return "cargo";
  }
}
