#!/usr/bin/env node
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dependency = resolve(root, "node_modules/@noble/hashes");
const manifest = JSON.parse(await readFile(resolve(dependency, "package.json"), "utf8"));
const ui = JSON.parse(await readFile(resolve(root, "packages/redevplugin-ui/package.json"), "utf8"));
if (manifest.version !== ui.dependencies["@noble/hashes"]) throw new Error("SHA-256 dependency must match its exact declared version");
const license = await readFile(resolve(dependency, "LICENSE"), "utf8");
const result = await build({
  stdin: {
    contents: 'export { sha256 } from "@noble/hashes/sha2.js";',
    resolveDir: root,
    sourcefile: "surface-integrity-entry.js",
  },
  bundle: true, format: "iife", globalName: "redevpluginIntegrity", platform: "browser",
  target: "es2022", minify: true, legalComments: "inline", write: false, logLevel: "silent",
});
if (result.outputFiles.length !== 1) throw new Error("expected one sandbox integrity bundle");
const source = `/* @noble/hashes ${manifest.version}\n${license}*/\n${result.outputFiles[0].text}`;
if (/<\/script/i.test(source)) throw new Error("integrity bundle must be safe inside an inline script");
const output = resolve(root, "packages/redevplugin-ui/src/surface-integrity.gen.ts");
const content = '// Code generated by scripts/build_surface_integrity.mjs; DO NOT EDIT.\n\n' +
  `export const surfaceIntegrityScript = ${JSON.stringify(source)};\n`;
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== content) throw new Error("surface integrity bundle is stale; run npm run surface-integrity:generate");
} else {
  await writeFile(output, content);
}
