#!/usr/bin/env node

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const targets = [
  {
    source: "demo/browser/opaque-plugin-worker.ts",
    output: "demo/browser/generated/opaque-plugin-worker.js",
  },
  {
    source: "demo/browser/real-plugin-worker.ts",
    output: "cmd/redevplugin/demo_assets/real-plugin-worker.js",
  },
  {
    source: "demo/browser/scaffold-plugin-worker.ts",
    output: "cmd/redevplugin/demo_assets/scaffold-plugin-worker.js",
  },
];

for (const target of targets) {
  const result = await build({
    entryPoints: [resolve(root, target.source)],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    legalComments: "none",
    sourcemap: false,
    write: false,
    logLevel: "silent",
  });
  if (result.outputFiles.length !== 1) {
    throw new Error(`expected one bundled worker for ${target.source}`);
  }
  const banner = "// Code generated by scripts/build_demo_workers.mjs; DO NOT EDIT.\n";
  const content = banner + result.outputFiles[0].text;
  const outputPath = resolve(root, target.output);
  if (checkOnly) {
    const current = await readFile(outputPath, "utf8").catch(() => "");
    if (current !== content) {
      throw new Error(`${target.output} is stale; run npm run demo:workers:build`);
    }
    continue;
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}
