#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import {
  assertSourceSnapshotUnchanged,
  buildCanonicalWasmArtifacts,
  canonicalRustImage,
  hashPaths,
  isCanonicalBuildHost,
  parseCanonicalWasmGeneratorArgs,
  readPinnedRustVersion,
  snapshotCanonicalCargoSources,
} from "./canonical_wasm_builder.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { checkOnly, forceCanonical } = parseCanonicalWasmGeneratorArgs(process.argv.slice(2));
const workerArtifactLockPath = "examples/plugins/worker-artifacts.lock.json";
const javascriptTargets = [
  ["examples/showcase/app.ts", "examples/showcase/app.js"],
  ["examples/plugin-ui/memos.ts", "examples/plugins/memos/ui/assets/app.js"],
  ["examples/plugin-ui/weather.ts", "examples/plugins/weather/ui/assets/app.js"],
  ["examples/plugin-ui/sky-strike.ts", "examples/plugins/sky-strike/ui/assets/app.js"],
];
const wasmTargets = [
  ["redevplugin-example-memos-worker", "redevplugin_example_memos_worker.wasm", "examples/plugins/memos/workers/memos.wasm"],
  ["redevplugin-example-weather-worker", "redevplugin_example_weather_worker.wasm", "examples/plugins/weather/workers/weather.wasm"],
  ["redevplugin-example-sky-strike-worker", "redevplugin_example_sky_strike_worker.wasm", "examples/plugins/sky-strike/workers/sky-strike.wasm"],
];
for (const [source, output] of javascriptTargets) {
  const result = await build({
    entryPoints: [resolve(root, source)],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    legalComments: "none",
    sourcemap: false,
    write: false,
    logLevel: "silent",
  });
  if (result.outputFiles.length !== 1) throw new Error(`expected one bundled worker for ${source}`);
  const content = `// Code generated by scripts/build_example_plugins.mjs; DO NOT EDIT.\n${result.outputFiles[0].text}`;
  await verifyOrWrite(output, Buffer.from(content));
}

const rustVersion = await readPinnedRustVersion(root);
const sourceSnapshotOptions = {
  root,
  rustVersion,
  packageNames: wasmTargets.map(([packageName]) => packageName),
  additionalPaths: [
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain.toml",
    "scripts/build_example_plugins.mjs",
    "scripts/canonical_wasm_builder.mjs",
  ],
  optionalPaths: [".cargo"],
};
const sourceSnapshotBefore = await snapshotCanonicalCargoSources(sourceSnapshotOptions);
if (!checkOnly || forceCanonical || isCanonicalBuildHost()) {
  const builtArtifacts = await buildCanonicalWasmArtifacts({
    root,
    rustVersion,
    targets: wasmTargets.map(([packageName, artifact]) => ({ packageName, artifact })),
    forceDocker: forceCanonical,
  });
  for (const [, artifact, output] of wasmTargets) {
    await verifyOrWrite(output, builtArtifacts.get(artifact));
  }
}

const sourceSnapshotAfter = await snapshotCanonicalCargoSources(sourceSnapshotOptions);
assertSourceSnapshotUnchanged(sourceSnapshotBefore, sourceSnapshotAfter);
const artifactHashes = await hashPaths(root, wasmTargets.map(([, , output]) => output));
const workerArtifactLock = Buffer.from(`${JSON.stringify({
  schema_version: "redevplugin.example_worker_artifacts.v1",
  rust_version: rustVersion,
  canonical_target: "wasm32-unknown-unknown",
  canonical_builder: "linux/amd64",
  canonical_image: canonicalRustImage(rustVersion),
  source_files: sourceSnapshotBefore.hashes,
  artifacts: artifactHashes,
}, null, 2)}\n`);
await verifyOrWrite(workerArtifactLockPath, workerArtifactLock);

async function verifyOrWrite(relativePath, content) {
  const outputPath = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(outputPath).catch(() => Buffer.alloc(0));
    if (!current.equals(content)) {
      throw new Error(`${relativePath} is stale; run npm run examples:generate`);
    }
    return;
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}
