#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import {
  assertSourceSnapshotUnchanged,
  buildCanonicalWasmArtifacts,
  canonicalRustImage,
  hashPaths,
  isCanonicalBuildHost,
  parseCanonicalWasmGeneratorArgs,
  readPinnedRustVersion,
  snapshotCanonicalCargoSources,
} from "./canonical_wasm_builder.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { checkOnly, forceCanonical } = parseCanonicalWasmGeneratorArgs(process.argv.slice(2));
const workerArtifactLockPath = "cmd/redevplugin/scaffold_assets/worker-artifacts.lock.json";
const workerOutputPath = "cmd/redevplugin/scaffold_assets/backend.wasm";
const result = await build({
  entryPoints: [resolve(root, "internal/scaffoldtemplate/plugin-worker.ts")],
  alias: {
    "@floegence/redevplugin-ui/plugin": resolve(root, "packages/redevplugin-ui/src/plugin.ts"),
  },
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  sourcemap: false,
  write: false,
  logLevel: "silent",
});
if (result.outputFiles.length !== 1) throw new Error("expected one bundled scaffold UI worker");
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/plugin-worker.js",
  Buffer.from(`// Code generated by scripts/build_scaffold_assets.mjs; DO NOT EDIT.\n${result.outputFiles[0].text}`),
);
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/plugin-worker.ts",
  await readFile(resolve(root, "internal/scaffoldtemplate/plugin-worker.ts")),
);
await verifyOrWrite(
  "cmd/redevplugin/scaffold_assets/worker-lib.rs",
  await readFile(resolve(root, "internal/scaffoldworker/src/lib.rs")),
);

const rustVersion = await readPinnedRustVersion(root);
const sourceSnapshotOptions = {
  root,
  rustVersion,
  packageNames: ["redevplugin-scaffold-worker"],
  additionalPaths: [
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain.toml",
    "scripts/build_scaffold_assets.mjs",
    "scripts/canonical_wasm_builder.mjs",
  ],
  optionalPaths: [".cargo"],
};
const sourceSnapshotBefore = await snapshotCanonicalCargoSources(sourceSnapshotOptions);
if (!checkOnly || forceCanonical || isCanonicalBuildHost()) {
  const artifact = "redevplugin_scaffold_worker.wasm";
  const builtArtifacts = await buildCanonicalWasmArtifacts({
    root,
    rustVersion,
    targets: [{ packageName: "redevplugin-scaffold-worker", artifact }],
    forceDocker: forceCanonical,
  });
  await verifyOrWrite(workerOutputPath, builtArtifacts.get(artifact));
}

const sourceSnapshotAfter = await snapshotCanonicalCargoSources(sourceSnapshotOptions);
assertSourceSnapshotUnchanged(sourceSnapshotBefore, sourceSnapshotAfter);
const artifactHashes = await hashPaths(root, [workerOutputPath]);
const workerArtifactLock = Buffer.from(`${JSON.stringify({
  schema_version: "redevplugin.scaffold_worker_artifacts.v1",
  rust_version: rustVersion,
  canonical_target: "wasm32-unknown-unknown",
  canonical_builder: "linux/amd64",
  canonical_image: canonicalRustImage(rustVersion),
  source_files: sourceSnapshotBefore.hashes,
  artifacts: artifactHashes,
}, null, 2)}\n`);
await verifyOrWrite(workerArtifactLockPath, workerArtifactLock);

async function verifyOrWrite(relativePath, content) {
  const outputPath = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(outputPath).catch(() => Buffer.alloc(0));
    if (!current.equals(content)) {
      throw new Error(`${relativePath} is stale; run npm run scaffold:generate`);
    }
    return;
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}
