#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.slice(2).includes("--check");
const javascriptTargets = [
  ["examples/showcase/app.ts", "examples/showcase/app.js"],
  ["examples/plugin-ui/memos.ts", "examples/plugins/memos/ui/assets/app.js"],
  ["examples/plugin-ui/weather.ts", "examples/plugins/weather/ui/assets/app.js"],
  ["examples/plugin-ui/sky-strike.ts", "examples/plugins/sky-strike/ui/assets/app.js"],
];
const wasmTargets = [
  ["redevplugin-example-memos-worker", "redevplugin_example_memos_worker.wasm", "examples/plugins/memos/workers/memos.wasm"],
  ["redevplugin-example-weather-worker", "redevplugin_example_weather_worker.wasm", "examples/plugins/weather/workers/weather.wasm"],
  ["redevplugin-example-sky-strike-worker", "redevplugin_example_sky_strike_worker.wasm", "examples/plugins/sky-strike/workers/sky-strike.wasm"],
];

for (const [source, output] of javascriptTargets) {
  const result = await build({
    entryPoints: [resolve(root, source)],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    legalComments: "none",
    sourcemap: false,
    write: false,
    logLevel: "silent",
  });
  if (result.outputFiles.length !== 1) throw new Error(`expected one bundled worker for ${source}`);
  const content = `// Code generated by scripts/build_example_plugins.mjs; DO NOT EDIT.\n${result.outputFiles[0].text}`;
  await verifyOrWrite(output, Buffer.from(content));
}

const cargo = await cargoPath();
for (const [packageName] of wasmTargets) {
  const result = spawnSync(cargo, ["build", "--release", "--target", "wasm32-unknown-unknown", "-p", packageName], {
    cwd: root,
    env: process.env,
    encoding: "utf8",
  });
  if (result.status !== 0) {
    process.stderr.write(result.stdout || "");
    process.stderr.write(result.stderr || "");
    throw new Error(`failed to build ${packageName}`);
  }
}
for (const [, artifact, output] of wasmTargets) {
  const content = await readFile(resolve(root, "target/wasm32-unknown-unknown/release", artifact));
  await verifyOrWrite(output, content);
}

async function verifyOrWrite(relativePath, content) {
  const outputPath = resolve(root, relativePath);
  if (checkOnly) {
    const current = await readFile(outputPath).catch(() => Buffer.alloc(0));
    if (!current.equals(content)) {
      throw new Error(`${relativePath} is stale; run npm run examples:generate`);
    }
    return;
  }
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
}

async function cargoPath() {
  const bundled = resolve(homedir(), ".cargo/bin/cargo");
  try {
    await access(bundled);
    return bundled;
  } catch {
    return "cargo";
  }
}
