#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { parse as parseYAML } from "yaml";

const root = resolve(import.meta.dirname, "..");
const checkOnly = process.argv.includes("--check");
const bridgeSchemaPath = join(root, "spec/plugin/bridge.schema.json");
const openAPIPath = join(root, "spec/openapi/plugin-platform.yaml");
const tsConstantsPath = join(root, "packages/redevplugin-ui/src/contracts.gen.ts");
const goRenderPolicyPath = join(root, "pkg/pluginpkg/opaque_surface_policy_gen.go");
const tsRenderPolicyPath = join(root, "packages/redevplugin-ui/src/opaque-surface-policy.gen.ts");
const routesPath = join(root, "testdata/contracts/routes.json");

const renderPolicy = await readRenderPolicy();
const pluginAPI = await readPluginAPI();
const outputs = new Map([
  [tsConstantsPath, renderTypeScriptConstants(pluginAPI)],
  [goRenderPolicyPath, formatGo(renderGoRenderPolicy(renderPolicy))],
  [tsRenderPolicyPath, renderTypeScriptRenderPolicy(renderPolicy)],
  [routesPath, await renderRoutes()],
]);

for (const [filename, content] of outputs) {
  if (checkOnly) {
    const current = await readFile(filename, "utf8").catch(() => "");
    if (current !== content) {
      throw new Error(`${relative(root, filename)} is stale; run npm run ui-contracts:generate`);
    }
  } else {
    await writeFile(filename, content);
  }
}

function renderTypeScriptConstants(pluginAPI) {
  return `// Code generated by scripts/generate_ui_contracts.mjs; DO NOT EDIT.\n\nexport const pluginAPIMajor = ${pluginAPI} as const;\n`;
}

async function readPluginAPI() {
  const source = JSON.parse(await readFile(join(root, "spec/plugin/plugin-api.json"), "utf8"));
  if (!isRecord(source) || !hasExactKeys(source, ["plugin_api"]) || !Number.isSafeInteger(source.plugin_api) || source.plugin_api < 1) {
    throw new Error("plugin API identity must contain one positive integer plugin_api");
  }
  return source.plugin_api;
}

async function readRenderPolicy() {
  const schema = JSON.parse(await readFile(bridgeSchemaPath, "utf8"));
  const policy = schema["x-redevplugin-render-policy"];
  const expectedKeys = [
    "max_message_bytes", "max_in_flight_requests", "max_renders_per_second",
    "max_render_depth", "max_render_nodes", "max_patch_operations",
    "max_attributes_per_element", "max_text_length", "max_attribute_value_length",
    "max_form_fields", "max_keyboard_bindings", "max_canvas_count", "max_canvas_dimension",
    "max_canvas_total_pixels", "max_canvas_pointer_events_per_second",
    "max_image_count", "max_image_dimension", "max_image_total_pixels",
    "worker_heartbeat_interval_ms", "worker_heartbeat_timeout_ms",
    "global_attributes", "tag_attributes", "safe_input_types",
  ];
  if (!isRecord(policy) || !hasExactKeys(policy, expectedKeys)) {
    throw new Error("bridge render policy must be a closed object");
  }
  const limits = {};
  for (const key of expectedKeys.filter((candidate) => candidate.startsWith("max_") || candidate.endsWith("_ms"))) {
    if (!Number.isSafeInteger(policy[key]) || policy[key] <= 0) {
      throw new Error(`bridge render policy ${key} must be a positive integer`);
    }
    limits[key] = policy[key];
  }
  const vnode = schema?.$defs?.element_vnode ?? schema?.$defs?.vnode?.oneOf?.[1];
  const allowedTags = vnode?.properties?.tag?.enum;
  const globalAttributes = policy.global_attributes;
  const safeInputTypes = policy.safe_input_types;
  if (![allowedTags, globalAttributes, safeInputTypes].every(isUniqueStringArray)) {
    throw new Error("bridge render policy lists must contain unique strings");
  }
  if (!isRecord(policy.tag_attributes)) {
    throw new Error("bridge render policy tag_attributes must be an object");
  }
  const tagAttributes = {};
  for (const [tag, attributes] of Object.entries(policy.tag_attributes)) {
    if (!allowedTags.includes(tag) || !isUniqueStringArray(attributes)) {
      throw new Error(`bridge render policy attributes are invalid for tag ${tag}`);
    }
    tagAttributes[tag] = attributes;
  }
  return { allowedTags, globalAttributes, tagAttributes, safeInputTypes, limits };
}

function renderGoRenderPolicy(policy) {
  const constantNames = {
    max_message_bytes: "opaqueSurfaceMaxMessageBytes",
    max_in_flight_requests: "opaqueSurfaceMaxInFlightRequests",
    max_renders_per_second: "opaqueSurfaceMaxRendersPerSecond",
    max_render_depth: "opaqueSurfaceMaxRenderDepth",
    max_render_nodes: "opaqueSurfaceMaxRenderNodes",
    max_patch_operations: "opaqueSurfaceMaxPatchOperations",
    max_attributes_per_element: "opaqueSurfaceMaxAttributesPerElement",
    max_text_length: "opaqueSurfaceMaxTextLength",
    max_attribute_value_length: "opaqueSurfaceMaxAttributeValueLength",
    max_form_fields: "opaqueSurfaceMaxFormFields",
    max_keyboard_bindings: "opaqueSurfaceMaxKeyboardBindings",
    max_canvas_count: "opaqueSurfaceMaxCanvasCount",
    max_canvas_dimension: "opaqueSurfaceMaxCanvasDimension",
    max_canvas_total_pixels: "opaqueSurfaceMaxCanvasTotalPixels",
    max_canvas_pointer_events_per_second: "opaqueSurfaceMaxCanvasPointerEventsPerSecond",
    max_image_count: "opaqueSurfaceMaxImageCount",
    max_image_dimension: "opaqueSurfaceMaxImageDimension",
    max_image_total_pixels: "opaqueSurfaceMaxImageTotalPixels",
    worker_heartbeat_interval_ms: "opaqueSurfaceWorkerHeartbeatIntervalMS",
    worker_heartbeat_timeout_ms: "opaqueSurfaceWorkerHeartbeatTimeoutMS",
  };
  const constants = Object.entries(constantNames)
    .map(([key, name]) => `\t${name} = ${policy.limits[key]}`)
    .join("\n");
  const renderSet = (values, indent = "\t") => values.map((value) => `${indent}${JSON.stringify(value)}: {},`).join("\n");
  const tagAttributes = Object.entries(policy.tagAttributes)
    .map(([tag, attributes]) => `\t${JSON.stringify(tag)}: {\n${renderSet(attributes, "\t\t")}\n\t},`)
    .join("\n");
  return `// Code generated by scripts/generate_ui_contracts.mjs; DO NOT EDIT.\n\npackage pluginpkg\n\nconst (\n${constants}\n)\n\nvar opaqueSurfaceAllowedTags = map[string]struct{}{\n${renderSet(policy.allowedTags)}\n}\n\nvar opaqueSurfaceGlobalAttributes = map[string]struct{}{\n${renderSet(policy.globalAttributes)}\n}\n\nvar opaqueSurfaceTagAttributes = map[string]map[string]struct{}{\n${tagAttributes}\n}\n\nvar opaqueSurfaceSafeInputTypes = map[string]struct{}{\n${renderSet(policy.safeInputTypes)}\n}\n`;
}

function renderTypeScriptRenderPolicy(policy) {
  return `// Code generated by scripts/generate_ui_contracts.mjs; DO NOT EDIT.\n\nexport const opaqueSurfaceAllowedTags = ${JSON.stringify(policy.allowedTags, null, 2)} as const;\nexport type OpaqueSurfaceAllowedTag = (typeof opaqueSurfaceAllowedTags)[number];\n\nexport const opaqueSurfaceGlobalAttributes = ${JSON.stringify(policy.globalAttributes, null, 2)} as const;\n\nexport const opaqueSurfaceTagAttributes = ${JSON.stringify(policy.tagAttributes, null, 2)} as const;\n\nexport const opaqueSurfaceSafeInputTypes = ${JSON.stringify(policy.safeInputTypes, null, 2)} as const;\n\nexport const opaqueSurfaceRenderLimits = ${JSON.stringify(policy.limits, null, 2)} as const;\n`;
}

async function renderRoutes() {
  const openAPI = parseYAML(await readFile(openAPIPath, "utf8"));
  if (!isRecord(openAPI) || !isRecord(openAPI.paths)) throw new Error("OpenAPI paths object is missing");
  const routes = [];
  for (const [path, pathItem] of Object.entries(openAPI.paths)) {
    if (!isRecord(pathItem)) continue;
    for (const method of ["delete", "get", "patch", "post", "put"]) {
      const operation = pathItem[method];
      if (!isRecord(operation)) continue;
      const effect = operation["x-redevplugin-route-effect"];
      if (effect !== "query" && effect !== "mutation") {
        throw new Error(`OpenAPI route ${method.toUpperCase()} ${path} has invalid or missing x-redevplugin-route-effect`);
      }
      routes.push({ method: method.toUpperCase(), path, effect });
    }
  }
  routes.sort((left, right) => left.path < right.path ? -1 : left.path > right.path ? 1 : left.method.localeCompare(right.method));
  return `${JSON.stringify(routes, null, 2)}\n`;
}

function formatGo(source) {
  const result = spawnSync("gofmt", { input: source, encoding: "utf8" });
  if (result.status !== 0) throw new Error(`gofmt failed: ${result.stderr || result.error}`);
  return result.stdout;
}

function hasExactKeys(value, expected) {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]);
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function isUniqueStringArray(value) {
  return Array.isArray(value) && value.length > 0 && value.every((item) => typeof item === "string" && item.length > 0) && new Set(value).size === value.length;
}
