#!/usr/bin/env node

import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseStrictJSON } from "./generate_platform_package_contracts.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = join(root, "spec/plugin/owner-scope-inventories-v1.json");
const outputPath = join(root, "pkg/ownerscope/inventory_gen.go");
const checkOnly = process.argv.slice(2).includes("--check");
const MAX_INVENTORY_BYTES = 1024 * 1024;
const expectedInventoryVersions = new Map([
  ["redeven-redevplugin-v0.1.0-v0.1.5-layout-v1", ["0.1.0", "0.1.1", "0.1.2", "0.1.3", "0.1.4", "0.1.5"]],
  ["redeven-redevplugin-v0.1.6-layout-v1", ["0.1.6"]],
  ["redeven-redevplugin-v0.2.x-layout-v1", ["0.2.0", "0.2.1", "0.2.2"]],
  ["redeven-redevplugin-v0.3.x-v0.4.x-layout-v1", ["0.3.0", "0.3.1", "0.3.2", "0.4.0", "0.4.1", "0.4.2", "0.4.3"]],
  ["redeven-redevplugin-v0.5.x-layout-v1", ["0.5.0", "0.5.1"]],
  ["redeven-redevplugin-v0.6.5-layout-v1", ["0.6.5"]],
]);

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}

async function main() {
  const output = await generateOwnerScopeInventories();
  if (checkOnly) {
    const current = await readFile(outputPath, "utf8").catch(() => "");
    if (current !== output) {
      throw new Error(`${relative(root, outputPath)} is stale; run npm run owner-scope-inventories:generate`);
    }
    return;
  }
  await writeFile(outputPath, output);
}

export async function generateOwnerScopeInventories() {
  const sourceBytes = await readFile(sourcePath);
  const registry = parseStrictJSON(sourceBytes, "owner scope inventory registry", MAX_INVENTORY_BYTES);
  validateRegistry(registry);
  if (!sourceBytes.equals(Buffer.from(`${JSON.stringify(registry, null, 2)}\n`))) {
    throw new Error("owner scope inventory registry must use canonical JSON formatting and key order");
  }

  const registrySHA256 = sha256(sourceBytes);
  const inventoryLiterals = registry.inventories.map((inventory) => `${renderInventory(inventory)},`).join("\n");
  const source = `// Code generated by scripts/generate_owner_scope_inventories.mjs; DO NOT EDIT.\n\npackage ownerscope\n\ntype builtInOwnerScopeRootEntry struct {\n\tPath string\n\tScope string\n\tDisposition string\n\tRequired bool\n}\n\ntype builtInOwnerScopeTreeRules struct {\n\tVariableTrees []string\n\tOptionalFiles []string\n}\n\ntype builtInOwnerScopeMigrationVersion struct {\n\tTable string\n\tVersions []int64\n}\n\ntype builtInOwnerScopeSQLiteDatabase struct {\n\tPath string\n\tRequired bool\n\tApplicationID int64\n\tUserVersion int64\n\tMigrationVersions []builtInOwnerScopeMigrationVersion\n\tSchemaObjectCount int\n\tSchemaSHA256 string\n}\n\ntype builtInOwnerScopeInventory struct {\n\tID string\n\tSHA256 string\n\tPlatformVersions []string\n\tRootEntries []builtInOwnerScopeRootEntry\n\tSQLiteDatabases []builtInOwnerScopeSQLiteDatabase\n\tTreeRules builtInOwnerScopeTreeRules\n}\n\nconst (\n\tRedevenLegacyInventoryV1 = ${JSON.stringify(registry.inventories[0].id)}\n\tRedevenV065InventoryV1 = ${JSON.stringify(registry.inventories.at(-1).id)}\n\tBuiltInInventoryRegistrySHA256 = ${JSON.stringify(registrySHA256)}\n)\n\nvar builtInOwnerScopeInventories = []builtInOwnerScopeInventory{\n${inventoryLiterals}\n}\n`;
  const formatted = spawnSync("gofmt", { input: source, encoding: "utf8" });
  if (formatted.status !== 0) {
    throw new Error(`gofmt failed: ${formatted.stderr || formatted.error}`);
  }
  return formatted.stdout;
}

export function validateRegistry(value) {
  if (!isRecord(value) || !hasExactKeys(value, ["schema_version", "inventories"]) || value.schema_version !== "owner-scope-inventory-v1") {
    throw new Error("owner scope inventory registry must be a closed v1 object");
  }
  if (!Array.isArray(value.inventories) || value.inventories.length !== expectedInventoryVersions.size) {
    throw new Error("owner scope inventory registry must contain the exact inventory family set");
  }

  const seenVersions = new Set();
  const seenFingerprints = new Set();
  for (let index = 0; index < value.inventories.length; index += 1) {
    const inventory = value.inventories[index];
    if (!isRecord(inventory) || !hasExactKeys(inventory, ["id", "platform_versions", "root_entries", "sqlite_databases", "tree_rules"])) {
      throw new Error(`owner scope inventory ${index} must be closed`);
    }
    const expectedVersions = expectedInventoryVersions.get(inventory.id);
    if (!expectedVersions || JSON.stringify(inventory.platform_versions) !== JSON.stringify(expectedVersions)) {
      throw new Error(`owner scope inventory ${index} has an unexpected id or version set`);
    }
    if (index > 0 && value.inventories[index - 1].id >= inventory.id) {
      throw new Error("owner scope inventories must be sorted by id");
    }
    for (const version of inventory.platform_versions) {
      if (seenVersions.has(version)) throw new Error(`platform version ${version} appears in multiple inventories`);
      seenVersions.add(version);
    }
    validateRootEntries(inventory.root_entries, inventory.id);
    validateTreeRules(inventory.tree_rules, inventory.root_entries, inventory.id);
    validateDatabases(inventory.sqlite_databases, inventory.id);
    const fingerprint = JSON.stringify({
      root_entries: inventory.root_entries,
      sqlite_databases: inventory.sqlite_databases.map((database) => ({
        path: database.path,
        required: database.required,
        application_id: database.application_id,
        user_version: database.user_version,
        migration_versions: database.migration_versions,
        schema_sha256: database.schema_sha256,
      })),
      tree_rules: inventory.tree_rules,
    });
    if (seenFingerprints.has(fingerprint)) {
      throw new Error(`owner scope inventory ${inventory.id} is ambiguous with another inventory`);
    }
    seenFingerprints.add(fingerprint);
  }
}

function validateRootEntries(entries, inventoryID) {
  if (!Array.isArray(entries) || entries.length < 1 || entries.length > 16) {
    throw new Error(`owner scope inventory ${inventoryID} has an invalid root entry set`);
  }
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index];
    if (!isRecord(entry) || !hasExactKeys(entry, ["path", "kind", "scope", "disposition", "required"])
        || !/^[a-z][a-z0-9-]{0,63}$/.test(entry.path)
        || entry.kind !== "directory" || entry.scope !== "durable" || entry.disposition !== "quarantine"
        || typeof entry.required !== "boolean"
        || (index > 0 && entries[index - 1].path >= entry.path)) {
      throw new Error(`owner scope inventory ${inventoryID} root entries must be closed, safe, sorted, and unique`);
    }
  }
  const databaseRoot = entries.find((entry) => entry.path === "db");
  if (!databaseRoot?.required) throw new Error(`owner scope inventory ${inventoryID} requires its database root`);
}

function validateTreeRules(rules, rootEntries, inventoryID) {
  if (!isRecord(rules) || !hasExactKeys(rules, [
    "allowed_kinds", "allow_sqlite_wal_shm", "reject_hardlinks", "reject_symlinks", "variable_trees", "optional_files",
  ]) || JSON.stringify(rules.allowed_kinds) !== JSON.stringify(["directory", "file"])
      || rules.allow_sqlite_wal_shm !== true || rules.reject_hardlinks !== true || rules.reject_symlinks !== true
      || !Array.isArray(rules.variable_trees) || !Array.isArray(rules.optional_files)) {
    throw new Error(`owner scope inventory ${inventoryID} has invalid tree rules`);
  }
  const expectedVariableTrees = rootEntries.map(({ path }) => path).filter((path) => path !== "db");
  if (JSON.stringify(rules.variable_trees) !== JSON.stringify(expectedVariableTrees)) {
    throw new Error(`owner scope inventory ${inventoryID} variable trees do not match its roots`);
  }
  for (let index = 0; index < rules.optional_files.length; index += 1) {
    const value = rules.optional_files[index];
    if (!/^db\/[a-z][a-z0-9_]*\.json$/.test(value)
        || (index > 0 && rules.optional_files[index - 1] >= value)) {
      throw new Error(`owner scope inventory ${inventoryID} optional files must be safe, sorted, and unique`);
    }
  }
}

function validateDatabases(databases, inventoryID) {
  if (!Array.isArray(databases) || databases.length === 0 || databases.length > 64) {
    throw new Error(`owner scope inventory ${inventoryID} must contain 1..64 SQLite databases`);
  }
  for (let index = 0; index < databases.length; index += 1) {
    const database = databases[index];
    if (!isRecord(database) || !hasExactKeys(database, ["path", "required", "application_id", "user_version", "migration_versions", "schema_objects", "schema_sha256"])) {
      throw new Error(`SQLite database ${inventoryID}[${index}] must be closed`);
    }
    if (!/^db\/[a-z][a-z0-9_]*\.sqlite$/.test(database.path)
        || typeof database.required !== "boolean"
        || (index > 0 && databases[index - 1].path >= database.path)) {
      throw new Error(`SQLite database paths for ${inventoryID} must be safe, sorted, and unique`);
    }
    if (!Number.isSafeInteger(database.application_id) || database.application_id < 0 || database.application_id > 0xffffffff
        || !Number.isSafeInteger(database.user_version) || database.user_version < 0 || database.user_version > 0x7fffffff) {
      throw new Error(`SQLite database ${database.path} has an invalid application or user version`);
    }
    validateMigrationVersions(database.migration_versions, database.path);
    validateSchemaObjects(database.schema_objects, database.path);
    const actualDigest = sha256(goJSONBytes(database.schema_objects));
    if (!/^[0-9a-f]{64}$/.test(database.schema_sha256) || actualDigest !== database.schema_sha256) {
      throw new Error(`SQLite database ${database.path} schema digest mismatch`);
    }
  }
}

function validateMigrationVersions(values, path) {
  if (!Array.isArray(values) || values.length > 16) throw new Error(`SQLite database ${path} has invalid migration versions`);
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!isRecord(value) || !hasExactKeys(value, ["table", "versions"])
        || !/^[a-z][a-z0-9_]{0,127}$/.test(value.table)
        || (index > 0 && values[index - 1].table >= value.table)) {
      throw new Error(`SQLite database ${path} migration tables must be closed, safe, sorted, and unique`);
    }
    if (!Array.isArray(value.versions) || value.versions.length === 0 || value.versions.length > 64) {
      throw new Error(`SQLite database ${path} migration version list is invalid`);
    }
    for (let versionIndex = 0; versionIndex < value.versions.length; versionIndex += 1) {
      const version = value.versions[versionIndex];
      if (!Number.isSafeInteger(version) || version < 0 || version > 0x7fffffff
          || (versionIndex > 0 && value.versions[versionIndex - 1] >= version)) {
        throw new Error(`SQLite database ${path} migration versions must be sorted and unique`);
      }
    }
  }
}

function validateSchemaObjects(values, path) {
  if (!Array.isArray(values) || values.length === 0 || values.length > 128) throw new Error(`SQLite database ${path} has invalid schema objects`);
  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];
    if (!isRecord(value) || !hasExactKeys(value, ["type", "name", "table_name", "sql"])
        || !["index", "table"].includes(value.type)
        || !/^[a-z][a-z0-9_]{0,127}$/.test(value.name)
        || !/^[a-z][a-z0-9_]{0,127}$/.test(value.table_name)
        || typeof value.sql !== "string" || value.sql.length === 0 || value.sql.length > 16384
        || value.sql !== value.sql.trim().split(/\s+/u).join(" ")) {
      throw new Error(`SQLite database ${path} contains an invalid schema object`);
    }
    if (index > 0) {
      const previous = `${values[index - 1].type}\0${values[index - 1].name}`;
      const current = `${value.type}\0${value.name}`;
      if (previous >= current) throw new Error(`SQLite database ${path} schema objects must be sorted and unique`);
    }
  }
}

function renderInventory(inventory) {
  const digest = sha256(Buffer.from(`${JSON.stringify(inventory)}\n`));
  const roots = inventory.root_entries.map((entry) =>
    `{Path: ${JSON.stringify(entry.path)}, Scope: ${JSON.stringify(entry.scope)}, Disposition: ${JSON.stringify(entry.disposition)}, Required: ${entry.required}}`,
  ).join(", ");
  const databases = inventory.sqlite_databases.map((database) => {
    const migrations = database.migration_versions.map((migration) =>
      `{Table: ${JSON.stringify(migration.table)}, Versions: []int64{${migration.versions.join(", ")}}}`,
    ).join(", ");
    return `{Path: ${JSON.stringify(database.path)}, Required: ${database.required}, ApplicationID: ${database.application_id}, UserVersion: ${database.user_version}, MigrationVersions: []builtInOwnerScopeMigrationVersion{${migrations}}, SchemaObjectCount: ${database.schema_objects.length}, SchemaSHA256: ${JSON.stringify(database.schema_sha256)}},`;
  }).join("\n");
  return `\t{\n\t\tID: ${JSON.stringify(inventory.id)},\n\t\tSHA256: ${JSON.stringify(digest)},\n\t\tPlatformVersions: []string{${inventory.platform_versions.map((value) => JSON.stringify(value)).join(", ")}},\n\t\tRootEntries: []builtInOwnerScopeRootEntry{${roots}},\n\t\tSQLiteDatabases: []builtInOwnerScopeSQLiteDatabase{\n${databases}\n\t\t},\n\t\tTreeRules: builtInOwnerScopeTreeRules{VariableTrees: []string{${inventory.tree_rules.variable_trees.map((value) => JSON.stringify(value)).join(", ")}}, OptionalFiles: []string{${inventory.tree_rules.optional_files.map((value) => JSON.stringify(value)).join(", ")}}},\n\t}`;
}

function goJSONBytes(value) {
  return Buffer.from(JSON.stringify(value).replaceAll("&", "\\u0026").replaceAll("<", "\\u003c").replaceAll(">", "\\u003e"));
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function hasExactKeys(value, expected) {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]);
}
