#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join, relative, resolve } from "node:path";

const [rawRootDir, rawOutFile] = process.argv.slice(2);

if (!rawRootDir || !rawOutFile) {
  console.error("usage: generate_third_party_notices.mjs <repo-root> <output-file>");
  process.exit(2);
}

const rootDir = resolve(rawRootDir);
const outFile = resolve(rawOutFile);

const rustPackages = readRustPackages(rootDir);
const npmPackages = readNpmPackages(join(rootDir, "package-lock.json"));
const goModules = readGoModules(rootDir);

const notice = [
  "# Third-Party Notices",
  "",
  "This file is generated by `scripts/generate_third_party_notices.mjs` during",
  "the ReDevPlugin release bundle build. It summarizes third-party dependency",
  "license metadata and keeps the dependency lockfiles as release evidence.",
  "",
  "Evidence files included in the release bundle:",
  "",
  "- `notices/go.sum`",
  "- `notices/package-lock.json`",
  "- `notices/Cargo.lock`",
  "",
  "The Rust dependency license allowlist is defined in `deny.toml` in the source",
  "repository and is enforced by CI with `cargo deny check`.",
  "",
  "## Rust Crates",
  "",
  table(
    ["Name", "Version", "License", "Source"],
    rustPackages.map((pkg) => [
      pkg.name,
      pkg.version,
      pkg.license || licenseFileLabel(pkg.license_file) || "UNKNOWN",
      sourceLabel(pkg.source),
    ]),
  ),
  "",
  "## npm Packages",
  "",
  table(
    ["Name", "Version", "License", "Scope"],
    npmPackages.map((pkg) => [
      pkg.name,
      pkg.version,
      pkg.license || "UNKNOWN",
      pkg.optional ? "optional" : pkg.dev ? "dev" : "runtime",
    ]),
  ),
  "",
  "## Go Modules",
  "",
  table(
    ["Path", "Version", "License Evidence"],
    goModules.map((mod) => [
      mod.path,
      mod.version || "(main)",
      mod.license_files.length > 0 ? mod.license_files.join(", ") : "UNKNOWN",
    ]),
  ),
  "",
].join("\n");

writeFileSync(outFile, notice);

function readRustPackages(root) {
  const metadataRaw = execFileSync("cargo", ["metadata", "--format-version", "1", "--locked"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, PATH: cargoPath() },
  });
  const metadata = JSON.parse(metadataRaw);
  return metadata.packages
    .filter((pkg) => typeof pkg.source === "string" && pkg.source.length > 0)
    .map((pkg) => ({
      name: pkg.name,
      version: pkg.version,
      license: pkg.license || "",
      license_file: pkg.license_file || "",
      source: pkg.source || "",
    }))
    .sort(compareBy("name", "version", "source"));
}

function readNpmPackages(lockfile) {
  const lock = JSON.parse(readFileSync(lockfile, "utf8"));
  const packages = lock.packages || {};
  const result = [];
  for (const [path, pkg] of Object.entries(packages)) {
    if (!path || !path.startsWith("node_modules/")) {
      continue;
    }
    const name = path.slice("node_modules/".length);
    result.push({
      name,
      version: String(pkg.version || ""),
      license: normalizeLicense(pkg.license),
      dev: Boolean(pkg.dev),
      optional: Boolean(pkg.optional),
    });
  }
  return result.sort(compareBy("name", "version"));
}

function readGoModules(root) {
  const raw = execFileSync("go", ["list", "-m", "-json", "all"], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, GOWORK: "off" },
  });
  const downloadedModules = readGoModuleDownloads(root);
  return parseGoListJSON(raw)
    .filter((mod) => !mod.Main)
    .map((mod) => ({
      path: mod.Path,
      version: mod.Version || "",
      license_files: scanLicenseFiles(
        mod.Dir || downloadedModules.get(moduleCacheKey(mod.Path, mod.Version || "")),
      ),
    }))
    .sort(compareBy("path", "version"));
}

function readGoModuleDownloads(root) {
  const tempDir = mkdtempSync(join(tmpdir(), "redevplugin-go-mod-"));
  try {
    copyFileSync(join(root, "go.mod"), join(tempDir, "go.mod"));
    if (existsSync(join(root, "go.sum"))) {
      copyFileSync(join(root, "go.sum"), join(tempDir, "go.sum"));
    }
    const raw = execFileSync(
      "go",
      ["mod", "download", "-json", `-modfile=${join(tempDir, "go.mod")}`, "all"],
      {
        cwd: root,
        encoding: "utf8",
        env: { ...process.env, GOWORK: "off" },
      },
    );
    const modules = new Map();
    for (const mod of parseGoListJSON(raw)) {
      if (mod.Path && mod.Version && mod.Dir) {
        modules.set(moduleCacheKey(mod.Path, mod.Version), mod.Dir);
      }
    }
    return modules;
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function moduleCacheKey(path, version) {
  return `${path}@${version}`;
}

function parseGoListJSON(raw) {
  const modules = [];
  let depth = 0;
  let current = "";
  let inString = false;
  let escaped = false;
  for (const char of raw) {
    if (depth > 0) {
      current += char;
    }
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }
    if (char === "\"") {
      inString = true;
      continue;
    }
    if (char === "{") {
      if (depth === 0) {
        current = "{";
      }
      depth += 1;
      continue;
    }
    if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        modules.push(JSON.parse(current));
        current = "";
      }
    }
  }
  return modules;
}

function scanLicenseFiles(dir) {
  if (!dir || !existsSync(dir) || !statSync(dir).isDirectory()) {
    return [];
  }
  const names = [];
  for (const entry of readdirSync(dir)) {
    const lower = entry.toLowerCase();
    if (
      lower === "license" ||
      lower.startsWith("license.") ||
      lower === "copying" ||
      lower.startsWith("copying.") ||
      lower === "notice" ||
      lower.startsWith("notice.")
    ) {
      names.push(entry);
    }
  }
  return names.sort();
}

function table(headers, rows) {
  const escapedRows = rows.map((row) => row.map(markdownCell));
  const escapedHeaders = headers.map(markdownCell);
  return [
    `| ${escapedHeaders.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...escapedRows.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}

function markdownCell(value) {
  return String(value ?? "")
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replaceAll("\n", " ")
    .trim();
}

function normalizeLicense(value) {
  if (Array.isArray(value)) {
    return value.join(" OR ");
  }
  return typeof value === "string" ? value : "";
}

function licenseFileLabel(path) {
  return path ? `license file: ${basename(path)}` : "";
}

function sourceLabel(source) {
  if (!source) {
    return "workspace";
  }
  if (source.startsWith("registry+")) {
    return source.slice("registry+".length);
  }
  return source;
}

function compareBy(...fields) {
  return (a, b) => {
    for (const field of fields) {
      const left = String(a[field] ?? "");
      const right = String(b[field] ?? "");
      const compared = left.localeCompare(right);
      if (compared !== 0) {
        return compared;
      }
    }
    return 0;
  };
}

function cargoPath() {
  const home = process.env.HOME || "";
  const cargoBin = home ? join(home, ".cargo", "bin") : "";
  return cargoBin && existsSync(cargoBin) ? `${cargoBin}${process.env.PATH ? `:${process.env.PATH}` : ""}` : process.env.PATH || "";
}
