#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const checkOnly = process.argv.includes("--check");
const version = (await readFile(join(root, "VERSION"), "utf8")).trim();
const pluginAPI = await readClosedPositiveInteger("spec/plugin/plugin-api.json", "plugin_api");
const internalWire = await readClosedPositiveInteger("spec/internal/runtime-wire.schema.json", "internal_wire", false);

if (!/^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/.test(version)) {
  throw new Error(`VERSION is not SemVer: ${JSON.stringify(version)}`);
}

const banner = "Code generated by scripts/generate_platform_identity.mjs; DO NOT EDIT.";
const outputs = new Map([
  ["pkg/version/platform_identity_gen.go", formatGo(`// ${banner}\n\npackage version\n\nconst developmentPlatformVersion = ${JSON.stringify(version)}\n`)],
  ["pkg/manifest/platform_identity_gen.go", formatGo(`// ${banner}\n\npackage manifest\n\nconst PluginAPIMajor uint16 = ${pluginAPI}\n`)],
  ["internal/resourceio/platform_identity_gen.go", formatGo(`// ${banner}\n\npackage resourceio\n\nconst PluginAPI uint16 = ${pluginAPI}\n`)],
  ["internal/runtimeclient/platform_identity_gen.go", formatGo(`// ${banner}\n\npackage runtimeclient\n\nconst InternalWire uint16 = ${internalWire}\n`)],
  ["crates/redevplugin-runtime/src/platform_identity_gen.rs", `// ${banner}\n\npub const PLUGIN_API: u16 = ${pluginAPI};\npub const INTERNAL_WIRE: u16 = ${internalWire};\n`],
  ["crates/redevplugin-worker-sdk/src/platform_identity_gen.rs", `// ${banner}\n\npub const PLUGIN_API: u16 = ${pluginAPI};\n`],
]);

for (const [relativePath, content] of outputs) {
  const filename = join(root, relativePath);
  if (checkOnly) {
    const current = await readFile(filename, "utf8").catch(() => "");
    if (current !== content) {
      throw new Error(`${relativePath} is stale; run npm run platform-identity:generate`);
    }
  } else {
    await writeFile(filename, content);
  }
}

async function readClosedPositiveInteger(relativePath, key, requireClosed = true) {
  const value = JSON.parse(await readFile(join(root, relativePath), "utf8"));
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${relativePath} must contain an object`);
  }
  if (requireClosed && (Object.keys(value).length !== 1 || !(key in value))) {
    throw new Error(`${relativePath} must contain only ${key}`);
  }
  if (!Number.isSafeInteger(value[key]) || value[key] < 1 || value[key] > 65535) {
    throw new Error(`${relativePath} ${key} must be a positive uint16`);
  }
  return value[key];
}

function formatGo(source) {
  const result = spawnSync("gofmt", { input: source, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`gofmt failed: ${result.stderr || result.error}`);
  }
  return result.stdout;
}
