import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "..");

test("platform identity projections are generated from canonical sources", async () => {
  const [
    version,
    pluginAPI,
    runtimeWire,
    goVersion,
    goManifestPluginAPI,
    goResourcePluginAPI,
    goWire,
    rustSDKPluginAPI,
    rustRuntimeIdentity,
  ] = await Promise.all([
    readFile(join(root, "VERSION"), "utf8").then((value) => value.trim()),
    readJSON("spec/plugin/plugin-api.json"),
    readJSON("spec/internal/runtime-wire.schema.json"),
    readFile(join(root, "pkg/version/platform_identity_gen.go"), "utf8"),
    readFile(join(root, "pkg/manifest/platform_identity_gen.go"), "utf8"),
    readFile(join(root, "internal/resourceio/platform_identity_gen.go"), "utf8"),
    readFile(join(root, "internal/runtimeclient/platform_identity_gen.go"), "utf8"),
    readFile(join(root, "crates/redevplugin-worker-sdk/src/platform_identity_gen.rs"), "utf8"),
    readFile(join(root, "crates/redevplugin-runtime/src/platform_identity_gen.rs"), "utf8"),
  ]);

  for (const projection of [
    goVersion,
    goManifestPluginAPI,
    goResourcePluginAPI,
    goWire,
    rustSDKPluginAPI,
    rustRuntimeIdentity,
  ]) {
    assert.match(projection, /Code generated by scripts\/generate_platform_identity\.mjs; DO NOT EDIT\./);
  }
  assert.match(goVersion, new RegExp(`developmentPlatformVersion = ${JSON.stringify(version)}`));
  assert.match(goManifestPluginAPI, new RegExp(`PluginAPIMajor uint16 = ${pluginAPI.plugin_api}`));
  assert.match(goResourcePluginAPI, new RegExp(`PluginAPI uint16 = ${pluginAPI.plugin_api}`));
  assert.match(goWire, new RegExp(`InternalWire uint16 = ${runtimeWire.internal_wire}`));
  assert.match(rustSDKPluginAPI, new RegExp(`PLUGIN_API: u16 = ${pluginAPI.plugin_api}`));
  assert.match(rustRuntimeIdentity, new RegExp(`PLUGIN_API: u16 = ${pluginAPI.plugin_api}`));
  assert.match(rustRuntimeIdentity, new RegExp(`INTERNAL_WIRE: u16 = ${runtimeWire.internal_wire}`));
});

async function readJSON(relativePath) {
  return JSON.parse(await readFile(join(root, relativePath), "utf8"));
}
