// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

package version

const (
	PluginUIProtocolVersion                  = "plugin-ui-v5"
	PluginHostProtocolVersion                = "plugin-host-v4"
	RustIPCVersion                           = "rust-ipc-v4"
	WASMABIVersion                           = "redevplugin-wasm-worker-v2"
	ManifestSchemaVersion                    = "manifest-v5"
	PackageSignatureSchemaVersion            = "package-signature-v1"
	ReleaseMetadataSchemaVersion             = "release-metadata-v5"
	SourcePolicySchemaVersion                = "source-policy-v1"
	SourceRevocationsSchemaVersion           = "source-revocations-v1"
	TokenTicketSchemaVersion                 = "token-ticket-v3"
	BridgeSchemaVersion                      = "bridge-v5"
	OpaqueSurfaceDocumentSchemaVersion       = "opaque-surface-document-v3"
	OpaqueSurfaceTransportSchemaVersion      = "opaque-surface-transport-v4"
	TargetClassifierVersion                  = "target-classifier-v2"
	NetworkGrantSchemaVersion                = "network-grant-v2"
	ResourceScopeSchemaVersion               = "resource-scope-v1"
	PluginPlatformOpenAPIVersion             = "plugin-platform-v6"
	CompatibilityManifestVersion             = "redevplugin.compatibility.v6"
	CompatibilitySchemaVersion               = "compatibility-manifest-v6"
	ReleaseManifestSchemaVersion             = "release-manifest-v4"
	WorkerInvocationSchemaVersion            = "worker-invocation-v3"
	HostCapabilityContractSchemaVersion      = "host-capability-contract-v1"
	HostCapabilityPinSchemaVersion           = "host-capability-pin-v1"
	HostCapabilityManifestSchemaVersion      = "host-capability-manifest-v1"
	HostCapabilityCompatibilitySchemaVersion = "host-capability-compatibility-v1"
	HostCapabilitySignatureSchemaVersion     = "host-capability-signature-v1"
	HostCapabilityNoticesSchemaVersion       = "host-capability-notices-v1"
	ErrorCodesSchemaVersion                  = "error-codes-v4"
	PerformanceContractVersion               = "performance-contract-v1"
	PerformanceEvidenceSchemaVersion         = "performance-evidence-v1"
	ContractRegistryVersion                  = "contract-registry-v1"
)

var generatedContractArtifacts = []ContractArtifact{
	{
		ID:      "plugin-platform-openapi",
		Path:    "spec/openapi/plugin-platform-v6.yaml",
		Version: "plugin-platform-v6",
		SHA256:  "944385206526b93761a77c17bd8d907131f13a9f92dd10b969866cac53b3074c",
	},
	{
		ID:      "manifest-schema",
		Path:    "spec/plugin/manifest-v5.schema.json",
		Version: "manifest-v5",
		SHA256:  "9695f6163aa539b9e3a933367c98850257c6d7bb8d61b36fd5f83b3ab61746f7",
	},
	{
		ID:      "package-signature-schema",
		Path:    "spec/plugin/package-signature-v1.schema.json",
		Version: "package-signature-v1",
		SHA256:  "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
	},
	{
		ID:      "release-metadata-schema",
		Path:    "spec/plugin/release-metadata-v5.schema.json",
		Version: "release-metadata-v5",
		SHA256:  "255ef3deb7d2758a43e69e533a08aa28106f8edc2e7385ab0aec0d50c1ef3d7a",
	},
	{
		ID:      "source-policy-schema",
		Path:    "spec/plugin/source-policy-v1.schema.json",
		Version: "source-policy-v1",
		SHA256:  "fb6a9c27e726378a28a9ff48ee47c40ede99fa95a524a308e2c762bebc4b9fe2",
	},
	{
		ID:      "source-revocations-schema",
		Path:    "spec/plugin/source-revocations-v1.schema.json",
		Version: "source-revocations-v1",
		SHA256:  "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
	},
	{
		ID:      "token-ticket-schema",
		Path:    "spec/plugin/token-ticket-v3.schema.json",
		Version: "token-ticket-v3",
		SHA256:  "17c7f2e7c7fcaa0eb43da7ecd92e4f36a918cc8149eec031d0231191d9245f16",
	},
	{
		ID:      "iframe-bridge-schema",
		Path:    "spec/plugin/bridge-v5.schema.json",
		Version: "bridge-v5",
		SHA256:  "b7bfeaad2eb34440881889d608297ef941e4d4a46c914c6bd19dfe4331d59729",
	},
	{
		ID:      "opaque-surface-document-schema",
		Path:    "spec/plugin/opaque-surface-document-v3.schema.json",
		Version: "opaque-surface-document-v3",
		SHA256:  "63419ff5b5a8890e14f97ca29aaae175b93daff61d4567c5bdff7f6e6a9e7450",
	},
	{
		ID:      "opaque-surface-transport-schema",
		Path:    "spec/plugin/opaque-surface-transport-v4.schema.json",
		Version: "opaque-surface-transport-v4",
		SHA256:  "70a32dc8bf281cea2c92492c466fd477070c62156a3f593d45eb460cde62dca2",
	},
	{
		ID:      "compatibility-manifest-schema",
		Path:    "spec/plugin/compatibility-manifest-v6.schema.json",
		Version: "compatibility-manifest-v6",
		SHA256:  "4f9e2a42c5a4893afad4027a5f29e4fc37843f450451dc5db26ac7919166a0db",
	},
	{
		ID:      "release-manifest-schema",
		Path:    "spec/plugin/release-manifest-v4.schema.json",
		Version: "release-manifest-v4",
		SHA256:  "b0a9e95b7bc819ee2a17a2d0bc4105b524e138945c11a19c77306a0a5351d63f",
	},
	{
		ID:      "worker-invocation-schema",
		Path:    "spec/plugin/worker-invocation-v3.schema.json",
		Version: "worker-invocation-v3",
		SHA256:  "f08af491cbf5e7b71d1aeafbeac9ae581ee5fc3bcb76184daec369f94bab3927",
	},
	{
		ID:      "host-capability-contract-schema",
		Path:    "spec/plugin/host-capability-contract-v1.schema.json",
		Version: "host-capability-contract-v1",
		SHA256:  "0a653e36d44104f1d16b06ee424648086c146f23c907b176bdf470ae73025485",
	},
	{
		ID:      "host-capability-pin-schema",
		Path:    "spec/plugin/host-capability-pin-v1.schema.json",
		Version: "host-capability-pin-v1",
		SHA256:  "20526a5934f0d85a3db7882492487266f09de5bcd176e2c7936f05d0b7fe0338",
	},
	{
		ID:      "host-capability-manifest-schema",
		Path:    "spec/plugin/host-capability-manifest-v1.schema.json",
		Version: "host-capability-manifest-v1",
		SHA256:  "5f13a8e5f918378b9cba9fdc133a9a75ba3a8311c30cb6a02ca0aba09035110e",
	},
	{
		ID:      "host-capability-compatibility-schema",
		Path:    "spec/plugin/host-capability-compatibility-v1.schema.json",
		Version: "host-capability-compatibility-v1",
		SHA256:  "361ebbf7009aeb66c763ecde46427b17b6cf7d2307c01886c5987a1f4f1762de",
	},
	{
		ID:      "host-capability-signature-schema",
		Path:    "spec/plugin/host-capability-signature-v1.schema.json",
		Version: "host-capability-signature-v1",
		SHA256:  "88cbc1d63afb7e289ca4f8b7c76f702b8d20156f7722c1b71f3ab9138a240a5e",
	},
	{
		ID:      "host-capability-notices-schema",
		Path:    "spec/plugin/host-capability-notices-v1.schema.json",
		Version: "host-capability-notices-v1",
		SHA256:  "6affd5d0ae90239f6fd08cbeddae4eef393efa2838c9e4935874ba3dc0e05948",
	},
	{
		ID:      "error-codes-schema",
		Path:    "spec/plugin/error-codes-v4.schema.json",
		Version: "error-codes-v4",
		SHA256:  "21afd88cfbdc62496f79a08011914f011f7df9c130c56fc3dd5a94e8910f5317",
	},
	{
		ID:      "performance-contract",
		Path:    "spec/plugin/performance-contract-v1.json",
		Version: "performance-contract-v1",
		SHA256:  "0754128585eea079c106e2215f92b45801adb2f51def8ee8c13238c39bcb9f17",
	},
	{
		ID:      "performance-evidence-schema",
		Path:    "spec/plugin/performance-evidence-v1.schema.json",
		Version: "performance-evidence-v1",
		SHA256:  "12865d1ebb165a923dfafad1881aa0f6c00f07ef430e1d16807ee66de451256f",
	},
	{
		ID:      "rust-ipc-schema",
		Path:    "spec/plugin/ipc-v4.schema.json",
		Version: "rust-ipc-v4",
		SHA256:  "eb66a442f1c45b8c75a0232f68632df8fb07929addc6da5b2f79970adf77662c",
	},
	{
		ID:      "wasm-worker-schema",
		Path:    "spec/plugin/wasm-worker-v2.schema.json",
		Version: "redevplugin-wasm-worker-v2",
		SHA256:  "00bf123f3a9ed932de4b71c180e2a5c34af0f82050defb271fedec42cf217902",
	},
	{
		ID:      "network-grant-schema",
		Path:    "spec/plugin/network-grant-v2.schema.json",
		Version: "network-grant-v2",
		SHA256:  "5fc1cfc3469a992e551fd392fab982abb6f95e456a1cb768ceca137f7c693abc",
	},
	{
		ID:      "resource-scope-schema",
		Path:    "spec/plugin/resource-scope-v1.schema.json",
		Version: "resource-scope-v1",
		SHA256:  "e6021bd576c7220ad5536645a7ad8e57ee7aeb9901c31a89444fa6b695d8dc6f",
	},
	{
		ID:      "target-classifier-fixture",
		Path:    "spec/plugin/target-classifier-v2.json",
		Version: "target-classifier-v2",
		SHA256:  "ae7336cce77a2e820f96f1cc309b93f8442c932dcebec25e3890d31cd098e2d1",
	},
	{
		ID:      "contract-registry",
		Path:    "spec/plugin/contract-registry-v1.json",
		Version: "contract-registry-v1",
		SHA256:  "86cc5ccce02ef00b6cf8b44af07ad3a82867ee039d8d82ffc704194ee2c62547",
	},
}
