// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

package version

const (
	PluginUIProtocolVersion                  = "plugin-ui-v5"
	PluginHostProtocolVersion                = "plugin-host-v4"
	RustIPCVersion                           = "rust-ipc-v4"
	WASMABIVersion                           = "redevplugin-wasm-worker-v2"
	ManifestSchemaVersion                    = "manifest-v5"
	PackageSignatureSchemaVersion            = "package-signature-v1"
	ReleaseMetadataSchemaVersion             = "release-metadata-v5"
	SourcePolicySchemaVersion                = "source-policy-v1"
	SourceRevocationsSchemaVersion           = "source-revocations-v1"
	TokenTicketSchemaVersion                 = "token-ticket-v2"
	BridgeSchemaVersion                      = "bridge-v5"
	OpaqueSurfaceDocumentSchemaVersion       = "opaque-surface-document-v3"
	OpaqueSurfaceTransportSchemaVersion      = "opaque-surface-transport-v4"
	TargetClassifierVersion                  = "target-classifier-v2"
	NetworkGrantSchemaVersion                = "network-grant-v2"
	ResourceScopeSchemaVersion               = "resource-scope-v1"
	PluginPlatformOpenAPIVersion             = "plugin-platform-v6"
	CompatibilityManifestVersion             = "redevplugin.compatibility.v6"
	CompatibilitySchemaVersion               = "compatibility-manifest-v6"
	ReleaseManifestSchemaVersion             = "release-manifest-v3"
	WorkerInvocationSchemaVersion            = "worker-invocation-v3"
	HostCapabilityContractSchemaVersion      = "host-capability-contract-v1"
	HostCapabilityPinSchemaVersion           = "host-capability-pin-v1"
	HostCapabilityManifestSchemaVersion      = "host-capability-manifest-v1"
	HostCapabilityCompatibilitySchemaVersion = "host-capability-compatibility-v1"
	HostCapabilitySignatureSchemaVersion     = "host-capability-signature-v1"
	HostCapabilityNoticesSchemaVersion       = "host-capability-notices-v1"
	ErrorCodesSchemaVersion                  = "error-codes-v4"
	PerformanceContractVersion               = "performance-contract-v1"
	PerformanceEvidenceSchemaVersion         = "performance-evidence-v1"
	ContractRegistryVersion                  = "contract-registry-v1"
)

var generatedContractArtifacts = []ContractArtifact{
	{
		ID:      "plugin-platform-openapi",
		Path:    "spec/openapi/plugin-platform-v6.yaml",
		Version: "plugin-platform-v6",
		SHA256:  "f81fb3b17798f9683b55b3d09b80ce1e56921ac80b54dd152aef1df990e1c1d1",
	},
	{
		ID:      "manifest-schema",
		Path:    "spec/plugin/manifest-v5.schema.json",
		Version: "manifest-v5",
		SHA256:  "9695f6163aa539b9e3a933367c98850257c6d7bb8d61b36fd5f83b3ab61746f7",
	},
	{
		ID:      "package-signature-schema",
		Path:    "spec/plugin/package-signature-v1.schema.json",
		Version: "package-signature-v1",
		SHA256:  "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
	},
	{
		ID:      "release-metadata-schema",
		Path:    "spec/plugin/release-metadata-v5.schema.json",
		Version: "release-metadata-v5",
		SHA256:  "255ef3deb7d2758a43e69e533a08aa28106f8edc2e7385ab0aec0d50c1ef3d7a",
	},
	{
		ID:      "source-policy-schema",
		Path:    "spec/plugin/source-policy-v1.schema.json",
		Version: "source-policy-v1",
		SHA256:  "fb6a9c27e726378a28a9ff48ee47c40ede99fa95a524a308e2c762bebc4b9fe2",
	},
	{
		ID:      "source-revocations-schema",
		Path:    "spec/plugin/source-revocations-v1.schema.json",
		Version: "source-revocations-v1",
		SHA256:  "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
	},
	{
		ID:      "token-ticket-schema",
		Path:    "spec/plugin/token-ticket-v2.schema.json",
		Version: "token-ticket-v2",
		SHA256:  "47fb014e8ffc899174f63259771ae7315e810e542948fcfef21b33443e0795a9",
	},
	{
		ID:      "iframe-bridge-schema",
		Path:    "spec/plugin/bridge-v5.schema.json",
		Version: "bridge-v5",
		SHA256:  "94cd15da6fd7fc56cfe81c014bd20099f1330e0ff04fe417422532581c701345",
	},
	{
		ID:      "opaque-surface-document-schema",
		Path:    "spec/plugin/opaque-surface-document-v3.schema.json",
		Version: "opaque-surface-document-v3",
		SHA256:  "63419ff5b5a8890e14f97ca29aaae175b93daff61d4567c5bdff7f6e6a9e7450",
	},
	{
		ID:      "opaque-surface-transport-schema",
		Path:    "spec/plugin/opaque-surface-transport-v4.schema.json",
		Version: "opaque-surface-transport-v4",
		SHA256:  "70a32dc8bf281cea2c92492c466fd477070c62156a3f593d45eb460cde62dca2",
	},
	{
		ID:      "compatibility-manifest-schema",
		Path:    "spec/plugin/compatibility-manifest-v6.schema.json",
		Version: "compatibility-manifest-v6",
		SHA256:  "8b8782db076e77c1e678b5f486694097e09911f70244b7c1a31f4814a86f51fb",
	},
	{
		ID:      "release-manifest-schema",
		Path:    "spec/plugin/release-manifest-v3.schema.json",
		Version: "release-manifest-v3",
		SHA256:  "c2e7eb7d4ac59b6523f635ca13adef21d94bb059dfab0d3a3300e049ef9bfe02",
	},
	{
		ID:      "worker-invocation-schema",
		Path:    "spec/plugin/worker-invocation-v3.schema.json",
		Version: "worker-invocation-v3",
		SHA256:  "562a7c0e7b8a5ded23e469f65020d66c129ebc3d5cfe2c7b573f3b53599f4780",
	},
	{
		ID:      "host-capability-contract-schema",
		Path:    "spec/plugin/host-capability-contract-v1.schema.json",
		Version: "host-capability-contract-v1",
		SHA256:  "a2318b01211aa6dbd8ca983f7ebca311619527aa4828a0ea0d201ebac7427292",
	},
	{
		ID:      "host-capability-pin-schema",
		Path:    "spec/plugin/host-capability-pin-v1.schema.json",
		Version: "host-capability-pin-v1",
		SHA256:  "20526a5934f0d85a3db7882492487266f09de5bcd176e2c7936f05d0b7fe0338",
	},
	{
		ID:      "host-capability-manifest-schema",
		Path:    "spec/plugin/host-capability-manifest-v1.schema.json",
		Version: "host-capability-manifest-v1",
		SHA256:  "5f13a8e5f918378b9cba9fdc133a9a75ba3a8311c30cb6a02ca0aba09035110e",
	},
	{
		ID:      "host-capability-compatibility-schema",
		Path:    "spec/plugin/host-capability-compatibility-v1.schema.json",
		Version: "host-capability-compatibility-v1",
		SHA256:  "361ebbf7009aeb66c763ecde46427b17b6cf7d2307c01886c5987a1f4f1762de",
	},
	{
		ID:      "host-capability-signature-schema",
		Path:    "spec/plugin/host-capability-signature-v1.schema.json",
		Version: "host-capability-signature-v1",
		SHA256:  "88cbc1d63afb7e289ca4f8b7c76f702b8d20156f7722c1b71f3ab9138a240a5e",
	},
	{
		ID:      "host-capability-notices-schema",
		Path:    "spec/plugin/host-capability-notices-v1.schema.json",
		Version: "host-capability-notices-v1",
		SHA256:  "6affd5d0ae90239f6fd08cbeddae4eef393efa2838c9e4935874ba3dc0e05948",
	},
	{
		ID:      "error-codes-schema",
		Path:    "spec/plugin/error-codes-v4.schema.json",
		Version: "error-codes-v4",
		SHA256:  "54f42bce8081b22d79b336e3690be4362a8147f150db47e6b36b49418ec19810",
	},
	{
		ID:      "performance-contract",
		Path:    "spec/plugin/performance-contract-v1.json",
		Version: "performance-contract-v1",
		SHA256:  "2af5644696e310089c0e530506c623632888e0774dde2b808d849a0a3f21fa28",
	},
	{
		ID:      "performance-evidence-schema",
		Path:    "spec/plugin/performance-evidence-v1.schema.json",
		Version: "performance-evidence-v1",
		SHA256:  "12865d1ebb165a923dfafad1881aa0f6c00f07ef430e1d16807ee66de451256f",
	},
	{
		ID:      "rust-ipc-schema",
		Path:    "spec/plugin/ipc-v4.schema.json",
		Version: "rust-ipc-v4",
		SHA256:  "437d03f0912288be85affdafc63a87e8a9acda190f888b253d61151626775124",
	},
	{
		ID:      "wasm-worker-schema",
		Path:    "spec/plugin/wasm-worker-v2.schema.json",
		Version: "redevplugin-wasm-worker-v2",
		SHA256:  "00bf123f3a9ed932de4b71c180e2a5c34af0f82050defb271fedec42cf217902",
	},
	{
		ID:      "network-grant-schema",
		Path:    "spec/plugin/network-grant-v2.schema.json",
		Version: "network-grant-v2",
		SHA256:  "37cb6f2913726f7202563238d7b322e4d539ef22498360603b8429081812382b",
	},
	{
		ID:      "resource-scope-schema",
		Path:    "spec/plugin/resource-scope-v1.schema.json",
		Version: "resource-scope-v1",
		SHA256:  "b307dacba983c5afb4422b9e63f844869920ed580afb526f4fc44b30ec1ec8bd",
	},
	{
		ID:      "target-classifier-fixture",
		Path:    "spec/plugin/target-classifier-v2.json",
		Version: "target-classifier-v2",
		SHA256:  "ae7336cce77a2e820f96f1cc309b93f8442c932dcebec25e3890d31cd098e2d1",
	},
	{
		ID:      "contract-registry",
		Path:    "spec/plugin/contract-registry-v1.json",
		Version: "contract-registry-v1",
		SHA256:  "7ce64105968ee340597e19eadd93b0be066210815a89acade759d4e5222758c9",
	},
}
