// Code generated by scripts/generate_contract_registry.mjs; DO NOT EDIT.

package version

const (
	PluginUIProtocolVersion                  = "plugin-ui-v3"
	PluginHostProtocolVersion                = "plugin-host-v2"
	RustIPCVersion                           = "rust-ipc-v2"
	WASMABIVersion                           = "redevplugin-wasm-worker-v2"
	ManifestSchemaVersion                    = "manifest-v3"
	PackageSignatureSchemaVersion            = "package-signature-v1"
	ReleaseMetadataSchemaVersion             = "release-metadata-v3"
	SourcePolicySchemaVersion                = "source-policy-v1"
	SourceRevocationsSchemaVersion           = "source-revocations-v1"
	TokenTicketSchemaVersion                 = "token-ticket-v2"
	BridgeSchemaVersion                      = "bridge-v3"
	OpaqueSurfaceDocumentSchemaVersion       = "opaque-surface-document-v2"
	OpaqueSurfaceTransportSchemaVersion      = "opaque-surface-transport-v2"
	TargetClassifierVersion                  = "target-classifier-v1"
	NetworkGrantSchemaVersion                = "network-grant-v1"
	PluginPlatformOpenAPIVersion             = "plugin-platform-v3"
	CompatibilityManifestVersion             = "redevplugin.compatibility.v3"
	CompatibilitySchemaVersion               = "compatibility-manifest-v3"
	ReleaseManifestSchemaVersion             = "release-manifest-v3"
	WorkerInvocationSchemaVersion            = "worker-invocation-v2"
	HostCapabilityContractSchemaVersion      = "host-capability-contract-v1"
	HostCapabilityPinSchemaVersion           = "host-capability-pin-v1"
	HostCapabilityManifestSchemaVersion      = "host-capability-manifest-v1"
	HostCapabilityCompatibilitySchemaVersion = "host-capability-compatibility-v1"
	HostCapabilitySignatureSchemaVersion     = "host-capability-signature-v1"
	HostCapabilityNoticesSchemaVersion       = "host-capability-notices-v1"
	ErrorCodesSchemaVersion                  = "error-codes-v1"
	ContractRegistryVersion                  = "contract-registry-v1"
)

var generatedContractArtifacts = []ContractArtifact{
	{
		ID:      "plugin-platform-openapi",
		Path:    "spec/openapi/plugin-platform-v3.yaml",
		Version: "plugin-platform-v3",
		SHA256:  "7a165176a1ac67054458c38b12deecffc8f6b4411e967bf8889bb2f1140c3b11",
	},
	{
		ID:      "manifest-schema",
		Path:    "spec/plugin/manifest-v3.schema.json",
		Version: "manifest-v3",
		SHA256:  "b5856b82a64c5654f15460191e74cc6f5c4a17018517ea1750840575f9c29881",
	},
	{
		ID:      "package-signature-schema",
		Path:    "spec/plugin/package-signature-v1.schema.json",
		Version: "package-signature-v1",
		SHA256:  "13951c0f6831ba28647774368c76a817868aeb7984628e2cf3dc4ad1b54f8284",
	},
	{
		ID:      "release-metadata-schema",
		Path:    "spec/plugin/release-metadata-v3.schema.json",
		Version: "release-metadata-v3",
		SHA256:  "a2fbe87dfcd57e7cb05410e829831a5500a6d127db22f4c28fd6187d56e7f4e7",
	},
	{
		ID:      "source-policy-schema",
		Path:    "spec/plugin/source-policy-v1.schema.json",
		Version: "source-policy-v1",
		SHA256:  "fb6a9c27e726378a28a9ff48ee47c40ede99fa95a524a308e2c762bebc4b9fe2",
	},
	{
		ID:      "source-revocations-schema",
		Path:    "spec/plugin/source-revocations-v1.schema.json",
		Version: "source-revocations-v1",
		SHA256:  "4c4132879a51b31e99775c979ca3ab43c2ee4c5c885f3ff1e7b43cd5ce8bc83d",
	},
	{
		ID:      "token-ticket-schema",
		Path:    "spec/plugin/token-ticket-v2.schema.json",
		Version: "token-ticket-v2",
		SHA256:  "f0342614f28b81045ac47d76d71753c8ee177f8143c14a711a0b1f5632e7835e",
	},
	{
		ID:      "iframe-bridge-schema",
		Path:    "spec/plugin/bridge-v3.schema.json",
		Version: "bridge-v3",
		SHA256:  "95d362d318327d09ecf6689c8fcfa38033dc5b3bf29b5e48da9d7290568e3b22",
	},
	{
		ID:      "opaque-surface-document-schema",
		Path:    "spec/plugin/opaque-surface-document-v2.schema.json",
		Version: "opaque-surface-document-v2",
		SHA256:  "abb0836bfb53089abd6522269265cc9f9e9bbc5b3cfc6d956404f6208b3e7238",
	},
	{
		ID:      "opaque-surface-transport-schema",
		Path:    "spec/plugin/opaque-surface-transport-v2.schema.json",
		Version: "opaque-surface-transport-v2",
		SHA256:  "7a96b009350b641ac56a1893d0eb74ed34d53bf50ee45df22f526e564a2fe6c9",
	},
	{
		ID:      "compatibility-manifest-schema",
		Path:    "spec/plugin/compatibility-manifest-v3.schema.json",
		Version: "compatibility-manifest-v3",
		SHA256:  "328612332a4226775e09aa19ed7d852ca59adb56467bf8c2a7d4f4bdfbf226d0",
	},
	{
		ID:      "release-manifest-schema",
		Path:    "spec/plugin/release-manifest-v3.schema.json",
		Version: "release-manifest-v3",
		SHA256:  "8c3fda908cd71169b2daf7d2a4e0b5b0c26a32e125a567304d872633fc05309b",
	},
	{
		ID:      "worker-invocation-schema",
		Path:    "spec/plugin/worker-invocation-v2.schema.json",
		Version: "worker-invocation-v2",
		SHA256:  "9a8843d19db04334525fd308a6b54fe26b12e3b4a0da46b417687e76629bd7d0",
	},
	{
		ID:      "host-capability-contract-schema",
		Path:    "spec/plugin/host-capability-contract-v1.schema.json",
		Version: "host-capability-contract-v1",
		SHA256:  "a2318b01211aa6dbd8ca983f7ebca311619527aa4828a0ea0d201ebac7427292",
	},
	{
		ID:      "host-capability-pin-schema",
		Path:    "spec/plugin/host-capability-pin-v1.schema.json",
		Version: "host-capability-pin-v1",
		SHA256:  "20526a5934f0d85a3db7882492487266f09de5bcd176e2c7936f05d0b7fe0338",
	},
	{
		ID:      "host-capability-manifest-schema",
		Path:    "spec/plugin/host-capability-manifest-v1.schema.json",
		Version: "host-capability-manifest-v1",
		SHA256:  "5f13a8e5f918378b9cba9fdc133a9a75ba3a8311c30cb6a02ca0aba09035110e",
	},
	{
		ID:      "host-capability-compatibility-schema",
		Path:    "spec/plugin/host-capability-compatibility-v1.schema.json",
		Version: "host-capability-compatibility-v1",
		SHA256:  "361ebbf7009aeb66c763ecde46427b17b6cf7d2307c01886c5987a1f4f1762de",
	},
	{
		ID:      "host-capability-signature-schema",
		Path:    "spec/plugin/host-capability-signature-v1.schema.json",
		Version: "host-capability-signature-v1",
		SHA256:  "88cbc1d63afb7e289ca4f8b7c76f702b8d20156f7722c1b71f3ab9138a240a5e",
	},
	{
		ID:      "host-capability-notices-schema",
		Path:    "spec/plugin/host-capability-notices-v1.schema.json",
		Version: "host-capability-notices-v1",
		SHA256:  "6affd5d0ae90239f6fd08cbeddae4eef393efa2838c9e4935874ba3dc0e05948",
	},
	{
		ID:      "error-codes-schema",
		Path:    "spec/plugin/error-codes-v1.schema.json",
		Version: "error-codes-v1",
		SHA256:  "1f59d2d4ddbd972d857f111aec98d31a9cf3d5baf96e57e152d5b68a1feea3d1",
	},
	{
		ID:      "rust-ipc-schema",
		Path:    "spec/plugin/ipc-v2.schema.json",
		Version: "rust-ipc-v2",
		SHA256:  "8c9dc1fe60da2399647efaad58b871860c278810ba4a6c357d904e2414a29aed",
	},
	{
		ID:      "wasm-worker-schema",
		Path:    "spec/plugin/wasm-worker-v2.schema.json",
		Version: "redevplugin-wasm-worker-v2",
		SHA256:  "d2ef05ffed74706cf0683a57665068c5bdf2b191a6c20cb876ec1049798afeaf",
	},
	{
		ID:      "network-grant-schema",
		Path:    "spec/plugin/network-grant-v1.schema.json",
		Version: "network-grant-v1",
		SHA256:  "e3ba8e7aa42267596b5570c1de60994a0912b125ea78427776db8092c2b3ea7b",
	},
	{
		ID:      "target-classifier-fixture",
		Path:    "spec/plugin/target-classifier-v1.json",
		Version: "target-classifier-v1",
		SHA256:  "7e9367d624c22d575ae5c118063c1cb0f0de6b5b0081eabcfc51c0357e4d14d7",
	},
	{
		ID:      "contract-registry",
		Path:    "spec/plugin/contract-registry-v1.json",
		Version: "contract-registry-v1",
		SHA256:  "ea303e08fb1a218cbf3696cc77c9e4b3cc8df9d0c5d2539e6b769b68884ef2b5",
	},
}
